// The Archive: a concrete bunker north of Calder held by the Keepers of the
// Archive, a scholarly order that hoards pre-war knowledge and technology.

import { defineMap, defineDialogues, defineQuests, defineObjScripts, defineEndings } from './registry';
import { defineItems } from '../data/items';
import { defineProtos, S } from '../data/protos';
import type { Ctx, NpcSpawn, ObjSpawn } from '../game/types';
import { G } from '../game/G';
import { hexDist } from '../core/hex';
import { addItem } from '../game/actors';

// --------------------------------------------------------------------- positions (generated by the map script)

const AP: Record<string, [number, number][]> = {
  // @gen archive_pos begin
  ada: [[9, 11]],
  aegisCase: [[46, 21]],
  apprentice: [[44, 14]],
  armLocker: [[35, 24], [39, 24], [43, 24]],
  armorer: [[44, 21]],
  armoryDoor: [[31, 21]],
  barracksShelf: [[15, 18]],
  barrel: [[16, 27], [32, 27], [47, 27]],
  bedroll: [[9, 31], [12, 34]],
  bench: [[29, 20]],
  blastDoor: [[24, 25]],
  bookcase: [[3, 2], [6, 2], [9, 2], [12, 2], [15, 2], [3, 5], [6, 5], [9, 5], [12, 5], [15, 5], [3, 9], [6, 9], [3, 12], [6, 12]],
  bunk: [[3, 18], [3, 24], [6, 18], [6, 24], [9, 18], [9, 24], [12, 18], [12, 24]],
  campfire: [[10, 33]],
  chair: [[12, 10], [12, 14]],
  deadtree: [[40, 29], [12, 30]],
  ent: [[8, 35]],
  entGate: [[24, 23]],
  farrowIn: [[11, 22]],
  footlocker: [[4, 20], [7, 20], [10, 20], [13, 20]],
  gateGuard: [[22, 27], [26, 27]],
  hallShelf: [[20, 9], [28, 9]],
  herald: [[26, 14]],
  initiate: [[8, 22]],
  innerGuard: [[21, 20], [27, 20]],
  lampIn: [[19, 18], [29, 18], [19, 14], [29, 14]],
  lampOut: [[21, 27], [27, 27]],
  lexicon: [[15, 8]],
  libLamp: [[14, 15], [5, 15]],
  mat: [[24, 22]],
  offDuty: [[15, 23]],
  partsShelf: [[19, 6]],
  petitioner: [[30, 34]],
  petitioner2: [[11, 31]],
  pile: [[36, 37], [42, 32]],
  pipe: [[27, 2], [28, 2]],
  rack: [[34, 18], [37, 18], [40, 18], [43, 18]],
  readTable: [[11, 10], [11, 14]],
  receiver: [[24, 2]],
  rock: [[34, 32], [44, 35], [6, 27]],
  rug: [[24, 14]],
  sandbags: [[18, 29], [19, 29], [20, 29], [28, 29], [29, 29], [30, 29], [22, 31], [26, 31]],
  scribe: [[8, 15]],
  sigGenerator: [[20, 2]],
  sigTerminal: [[29, 5]],
  sign: [[33, 28]],
  signalDoor: [[24, 8]],
  statue: [[21, 15], [27, 15]],
  tank: [[45, 30]],
  tent: [[13, 36], [6, 31]],
  tomas: [[40, 7]],
  truck: [[38, 34]],
  varga: [[24, 11]],
  vargaTable: [[24, 12]],
  vestLocker: [[18, 23], [30, 23]],
  workbench: [[38, 8], [42, 8]],
  wsCrate: [[40, 2]],
  wsGenerator: [[34, 3]],
  wsLamp: [[47, 10]],
  wsShelf: [[36, 12], [45, 12]],
  wsTerminal: [[33, 15]],
  wsToolbox: [[46, 3]],
  yardCrate: [[15, 33]],
  // @gen archive_pos end
};
const ap = (k: string): [number, number] => {
  const v = AP[k];
  if (!v || !v.length) {
    console.warn('archive: no position', k);
    return [1, 1];
  }
  return v[0];
};
const props = (k: string, o: Omit<ObjSpawn, 'at'>): ObjSpawn[] => (AP[k] ?? []).map((p) => ({ ...o, at: p }));

// --------------------------------------------------------------------- items, creatures, quests

defineItems([
  { id: 'dataSpindle', name: 'Data Spindle', type: 'misc', weight: 0.5, value: 0, icon: 'holotape', quest: true, desc: 'A thumb-length rod of archival glass in a steel sleeve, etched "CALDER MUNICIPAL TECHNICAL - VAULT B". A thread of light runs through it when you tilt it to the sun.' },
  { id: 'ar_signet', name: 'Initiate\'s Signet', type: 'key', weight: 0, value: 0, icon: 'keycard', quest: true, desc: 'A steel ring with a magnetic bezel, the open book of the Keepers of the Archive cut into its face. It opens the armory and the signal room.' },
]);

defineProtos([
  { id: 'ar_sentinel', name: 'Keeper Sentinel', desc: 'a Keeper sentinel in scuffed plate, laser carbine at port arms', look: { body: 'human', skin: '#c89468', hair: '#333', hairStyle: 'helmet', outfit: '#4a4e56', outfit2: '#8a2a24' }, stats: S(6, 7, 6, 4, 6, 6, 5), xp: 170, skills: { energy: 80, smallGuns: 65, melee: 55, unarmed: 50 }, equip: ['laserRifle', 'metalArmor'], inv: [{ id: 'cell', n: 20 }, { id: 'hypo', n: 1, chance: 40 }], team: 'keepers', hostile: false },
  { id: 'ar_sentinelF', name: 'Keeper Sentinel', desc: 'a Keeper sentinel in composite plates, laser pistol holstered', look: { body: 'human', female: true, skin: '#8a5a3a', hair: '#1a1a1a', hairStyle: 'helmet', outfit: '#4a4e56', outfit2: '#8a2a24' }, stats: S(5, 7, 6, 5, 6, 7, 5), xp: 170, skills: { energy: 80, smallGuns: 65, melee: 50 }, equip: ['laserPistol', 'combatArmor'], inv: [{ id: 'cell', n: 20 }], team: 'keepers', hostile: false },
  { id: 'ar_scribe', name: 'Keeper Scribe', desc: 'a Keeper scribe in a long grey coat, ink on every finger', look: { body: 'human', skin: '#d0a078', hair: '#4a3020', hairStyle: 'short', outfit: '#5a5a60', outfit2: '#8a2a24' }, stats: S(4, 6, 5, 5, 8, 5, 5), xp: 60, skills: { energy: 50, science: 80, repair: 60 }, equip: ['laserPistol'], inv: [{ id: 'cell', n: 10 }], team: 'keepers', hostile: false },
]);

defineQuests([
  { id: 'ar_trial', title: 'Trial of the Archive', area: 'archive', xp: 1200, desc: 'The Keepers of the Archive accept as initiates only those who bring them a pre-war data spindle. There is a vault of them in the Calder technical library annex.' },
  { id: 'ar_relay', title: 'The Listening Post', area: 'archive', xp: 1000, desc: 'The Keepers\' long-range receiver has been dead for two winters. Scribe-Commander Varga wants it working, to hear the signal from the south again.' },
  { id: 'ar_farrow', title: 'A Word for Farrow', area: 'archive', xp: 200, desc: 'Farrow, a young petitioner camped outside the Archive, wants to become a Keeper. An initiate\'s word might get him in.' },
]);

// --------------------------------------------------------------------- helpers

function admit(c: Ctx, why: string) {
  if (!c.flag('ar_admitted')) {
    c.set('ar_admitted', why);
    c.xp(100);
  }
  const o = c.obj('ar_blastDoor');
  if (o) {
    o.locked = 0;
    o.open = true;
    if (G.map) G.map.version++;
  }
  c.sound('hatch');
}

function isInitiate(c: Ctx) {
  return !!c.flag('ar_initiate');
}

function knowsSecrets(c: Ctx) {
  return isInitiate(c) || !!c.flag('ar_impressed');
}

function stockTomas(c: Ctx) {
  if (!isInitiate(c) || c.flag('ar_stocked')) return;
  const t = c.npc('ar_tomas');
  if (!t) return;
  c.set('ar_stocked');
  for (const [id, n] of [['laserRifle', 2], ['combatArmor', 1], ['cell', 120], ['superHypo', 2], ['fusion', 20], ['plasmaRifle', 1], ['medkit', 1]] as [string, number][]) addItem(t, id, n);
}

function initiate(c: Ctx) {
  if (isInitiate(c)) return;
  c.take('dataSpindle');
  c.questDone('ar_trial', 'I brought Scribe-Commander Varga a data spindle from Calder and was made an initiate of the Archive.');
  c.set('ar_initiate');
  c.give('ar_signet');
  c.karma(10);
  c.rep('archive', 25);
  for (const id of ['ar_armoryDoor', 'ar_signalDoor']) {
    const o = c.obj(id);
    if (o) o.locked = 0;
  }
  stockTomas(c);
}

function reveal(c: Ctx, what: 'kessler' | 'cathedral', note: string) {
  const flag = what === 'kessler' ? 'ar_toldKessler' : 'ar_toldCathedral';
  c.reveal(what);
  if (!c.flag(flag)) {
    c.set(flag);
    c.xp(150);
    if (c.questState('grafted') === 'active') c.quest('grafted', note);
  }
}

function keepersWatching(radius: number) {
  const m = G.map;
  if (!m) return [];
  const p = G.state.player;
  return m.actors.filter((a) => a.team === 'keepers' && !a.dead && !a.hostile && hexDist(a, p) <= radius);
}

function canPledge(c: Ctx) {
  return isInitiate(c) && (c.flag('act2') || c.flag('shelter7Logs')) && !c.flag('ar_pledged');
}

const KEEPER_BARKS = ['Knowledge is a trust, not a trade.', 'Mind the stacks. Some of those pages are older than the Basin.', 'Cells don\'t grow on trees, initiate.', 'Record everything.', 'Outsiders touch nothing.', 'The door holds. The door always holds.'];

// --------------------------------------------------------------------- the map

defineMap({
  id: 'archive',
  name: 'The Archive',
  area: 'archive',
  outdoor: true,
  floor: 'concrete',
  floor2: 'sand',
  wall: 'concrete',
  wall2: 'fence',
  music: 'shelter',
  legend: {
    '"': { floor: 'sand', decor: 'scrub' },
    '-': { floor: 'carpet' },
    '|': { wall: 'fence', floor: 'sand' },
    '>': { floor: 'sand', exit: 'out' },
  },
  rows: [
    // @gen archive begin
    '##################################################',
    '##################################################',
    '##---------------#_____________#________________##',
    '##---------------#_____________#________________##',
    '##---------------#_____________#________________##',
    '##---------------#_____________#________________##',
    '##---------------#_____________#________________##',
    '##---------------#_____________#________________##',
    '##---------------#######+#######________________##',
    '##---------------#=============#________________##',
    '##---------------#=============#________________##',
    '##---------------#=============#________________##',
    '##---------------+=============+________________##',
    '##---------------#=============#________________##',
    '##---------------#=============#________________##',
    '##---------------#=============#________________##',
    '##---------------#=============#________________##',
    '########################+#########################',
    '##...............#.............#________________##',
    '##...............#.............#________________##',
    '##...............#.............#________________##',
    '##...............+.............+________________##',
    '##...............#.............#________________##',
    '##...............#.............#________________##',
    '##...............#.............#________________##',
    '|#######################+########################|',
    '||,,,,,,,,,,,,",,,,,,,,,,,",,,,,,,,,,,,,,,,,,",,,|',
    '||,,,,,,,,,,,,,,,,,,",",,,,,,",,,,,,",,,",,,,,,,,|',
    '||,",,,,,,,,,,,,,,,,,,,,,,",,,,,,,,",,,,,",,,,",,|',
    '>,,,,,,,,,,,,",,,,,,,,",,,,,,,,,,,,,,,",,,,,,,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|',
    '>,,,,,,,,,,,,,,,",,,,,,"",,,,,,,,,,",,,,,,,,,,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,,,,,",,"",,,,,,,,,,,,,,,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,",,,,,",,,,,,,,,,,,,,,,,,,,|',
    '>,,,,"",,,,,,,,,,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,,,,,,,",,,,,,,,,,,,",,,,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",,,,,|',
    '>,,,,,,,,,,,,,,,,,,,,,,,",,,,,,,,,,,,",,,,,",,,,,|',
    '>,,,",,,,,,,,,,,,,,",,,",,,,,,,,,,,,,,,,",,,,,,,,|',
    '|||>>>>>>>>>>>>>>>>>>>>>||||||||||||||||||||||||||',
    // @gen archive end
  ],
  entrances: { default: ap('ent'), gate: ap('entGate') },
  exits: { out: { to: 'world' } },
  objects: [
    { kind: 'gate', at: ap('blastDoor'), id: 'ar_blastDoor', name: 'blast gate', locked: 95, onUse: 'ar_blastdoor', desc: 'the Archive\'s blast gate: a grille of steel bars on hydraulic rams, an open book welded into its centre in rusted iron' },
    { kind: 'door', at: ap('armoryDoor'), id: 'ar_armoryDoor', name: 'armory door', locked: 95, key: 'ar_signet', onUse: 'ar_guarded', desc: 'a vault door with a magnetic signet plate. ARMORY - INITIATES ONLY' },
    { kind: 'door', at: ap('signalDoor'), id: 'ar_signalDoor', name: 'signal room door', locked: 80, key: 'ar_signet', onUse: 'ar_guarded', desc: 'a steel door with a signet plate and a hand-painted lightning bolt' },
    // yard
    ...props('sandbags', { kind: 'sandbags' }),
    ...props('lampOut', { kind: 'lamp' }),
    ...props('rock', { kind: 'rock' }),
    ...props('deadtree', { kind: 'deadtree' }),
    { kind: 'car', at: ap('truck'), name: 'burnt-out truck', tint: '#5a5a4a' },
    { kind: 'crate', at: ap('yardCrate'), name: 'petitioners\' crate', inv: [{ id: 'water', n: 1 }, { id: 'jerky', n: 2 }] },
    { kind: 'sign', at: ap('sign'), name: 'sign', desc: 'a painted sign: "THE ARCHIVE. PETITIONERS WAIT HERE. DO NOT APPROACH THE DOOR." Someone has added underneath: "OR ELSE"' },
    { kind: 'campfire', at: ap('campfire') },
    ...props('tent', { kind: 'tent', tint: '#7a6a4a' }),
    ...props('bedroll', { kind: 'bedroll' }),
    ...props('barrel', { kind: 'barrel', tint: '#4a5a4a' }),
    ...props('pile', { kind: 'pile', name: 'scrap heap', inv: [{ id: 'scrapMetal', n: 1 }] }),
    { kind: 'tank', at: ap('tank'), name: 'water tower', tint: '#6a6a60' },
    // vestibule
    ...props('vestLocker', { kind: 'locker', name: 'sentinel locker', locked: 50, inv: [{ id: 'cell', n: 12 }] }),
    ...props('lampIn', { kind: 'lamp' }),
    { kind: 'table', at: ap('bench'), tint: '#5a5a5a' },
    { kind: 'mat', at: ap('mat') },
    // barracks
    ...props('bunk', { kind: 'bunk' }),
    ...props('footlocker', { kind: 'footlocker', inv: [{ id: 'jerky', n: 1 }] }),
    { kind: 'shelf', at: ap('barracksShelf'), inv: [{ id: 'hypo', n: 1 }, { id: 'cell', n: 10 }] },
    // armory
    ...props('rack', { kind: 'rack', name: 'weapon rack' }),
    { kind: 'locker', at: AP.armLocker[0], name: 'armory locker', locked: 60, inv: [{ id: 'cell', n: 40 }, { id: 'laserPistol', n: 1 }] },
    { kind: 'locker', at: AP.armLocker[1], name: 'armory locker', locked: 60, inv: [{ id: 'metalArmor', n: 1 }, { id: 'hypo', n: 2 }] },
    { kind: 'locker', at: AP.armLocker[2], name: 'armory locker', locked: 60, inv: [{ id: 'fragGrenade', n: 3 }, { id: 'cell', n: 30 }] },
    { kind: 'statue', at: ap('aegisCase'), name: 'armor stand', onUse: 'ar_aegisstand', desc: 'an empty armor stand, sized for something big' },
    // hall of record
    { kind: 'table', at: ap('vargaTable'), name: 'the Commander\'s table', tint: '#4a3a2a' },
    ...props('hallShelf', { kind: 'bookcase', name: 'card index' }),
    ...props('statue', { kind: 'statue', name: 'statue of a pre-war signals officer' }),
    { kind: 'rug', at: ap('rug'), tint: '#6a2a24' },
    // library
    ...props('bookcase', { kind: 'bookcase', name: 'stacks' }),
    ...props('readTable', { kind: 'table', tint: '#5a4030' }),
    ...props('chair', { kind: 'chair' }),
    ...props('libLamp', { kind: 'lamp' }),
    { kind: 'terminal', at: ap('lexicon'), id: 'ar_lexicon', name: 'the Lexicon', onUse: 'ar_lexicon' },
    // signal room
    { kind: 'console', at: ap('receiver'), id: 'ar_receiver', name: 'long-range receiver', onUse: 'ar_receiver' },
    { kind: 'generator', at: ap('sigGenerator'), name: 'receiver generator' },
    ...props('pipe', { kind: 'pipe', name: 'antenna trunk' }),
    { kind: 'shelf', at: ap('partsShelf'), name: 'parts shelf', inv: [{ id: 'scrapElectronics', n: 1 }] },
    { kind: 'terminal', at: ap('sigTerminal'), id: 'ar_sigTerm', name: 'signal log terminal', onUse: 'ar_siglog' },
    // workshop
    { kind: 'generator', at: ap('wsGenerator') },
    { kind: 'toolbox', at: ap('wsToolbox'), inv: [{ id: 'scrapElectronics', n: 1 }] },
    { kind: 'crate', at: ap('wsCrate'), name: 'parts crate', inv: [{ id: 'scrapMetal', n: 4 }] },
    ...props('workbench', { kind: 'table', name: 'workbench', tint: '#6a6a60' }),
    ...props('wsShelf', { kind: 'shelf', name: 'parts shelf' }),
    { kind: 'terminal', at: ap('wsTerminal'), id: 'ar_wsTerm', name: 'workshop terminal', onUse: 'ar_wsterm' },
    { kind: 'lamp', at: ap('wsLamp') },
  ],
  npcs: [
    { proto: 'ar_sentinelF', id: 'ar_varga', name: 'Scribe-Commander Odile Varga', at: ap('varga'), dialog: 'ar_varga', team: 'keepers', equip: ['laserPistol', 'combatArmor'], look: { skin: '#d8b090', hair: '#9a9a9a', hairStyle: 'bun' } },
    { proto: 'merchant', id: 'ar_tomas', name: 'Brother Tomas', at: ap('tomas'), dialog: 'ar_tomas', team: 'keepers', barter: true, equip: ['laserPistol'], look: { skin: '#9a6a48', hairStyle: 'bald', beard: true, hair: '#3a2a1a', outfit: '#4a4e56', outfit2: '#8a2a24' },
      inv: [{ id: 'cell', n: 40 }, { id: 'laserPistol', n: 1 }, { id: 'metalArmor', n: 1 }, { id: 'hypo', n: 3 }, { id: 'scrapElectronics', n: 4 }, { id: 'toolkit', n: 1 }, { id: 'geiger', n: 1 }, { id: 'scrip', n: 600 }] },
    { proto: 'ar_scribe', id: 'ar_ada', name: 'Sister Ada', at: ap('ada'), dialog: 'ar_ada', team: 'keepers', look: { female: true, skin: '#c89468', hair: '#6a3a1a', hairStyle: 'bun', outfit: '#5a5a60' } },
    { proto: 'ar_sentinel', id: 'ar_gate0', name: 'Sentinel Brask', at: AP.gateGuard[0], dialog: 'ar_gate', team: 'keepers' },
    { proto: 'ar_sentinelF', id: 'ar_gate1', name: 'Sentinel Oduya', at: AP.gateGuard[1], dialog: 'ar_gate', team: 'keepers' },
    ...AP.innerGuard.map((p, i): NpcSpawn => ({ proto: i ? 'ar_sentinelF' : 'ar_sentinel', id: 'ar_inner' + i, at: p, dialog: 'ar_sentinel', team: 'keepers' })),
    { proto: 'ar_scribe', id: 'ar_linnet', name: 'Scribe Linnet', at: ap('herald'), dialog: 'ar_linnet', team: 'keepers', look: { female: true, hair: '#c8a040', hairStyle: 'long' } },
    { proto: 'ar_scribe', id: 'ar_hollis', name: 'Scribe Hollis', at: ap('scribe'), dialog: 'ar_hollis', team: 'keepers', wander: 3 },
    { proto: 'ar_sentinelF', id: 'ar_hedda', name: 'Armorer Hedda Kray', at: ap('armorer'), dialog: 'ar_hedda', team: 'keepers', look: { hairStyle: 'short', hair: '#8a3a1a', skin: '#e0b898' } },
    { proto: 'ar_scribe', id: 'ar_dace', name: 'Apprentice Dace', at: ap('apprentice'), dialog: 'ar_dace', team: 'keepers', look: { scale: 0.9, hair: '#1a1a1a' } },
    { proto: 'ar_sentinel', id: 'ar_offduty', name: 'Sentinel Marl', at: ap('offDuty'), dialog: 'ar_sentinel', team: 'keepers', equip: ['laserPistol'] },
    { proto: 'ar_scribe', id: 'ar_rook', name: 'Initiate Rook', at: ap('initiate'), dialog: 'ar_rook', team: 'keepers', wander: 3, look: { skin: '#6a4028', hair: '#101010' } },
    { proto: 'villager', id: 'ar_farrow', name: 'Farrow', at: ap('petitioner2'), dialog: 'ar_farrow', team: 'neutral', if: (c) => !c.flag('ar_farrowVouched'), look: { scale: 0.9, skin: '#c89468', hair: '#8a5a2a', outfit: '#6a5a40' } },
    { proto: 'ar_scribe', id: 'ar_farrowIn', name: 'Initiate Farrow', at: ap('farrowIn'), dialog: 'ar_farrow', team: 'keepers', if: (c) => !!c.flag('ar_farrowVouched'), look: { scale: 0.9, skin: '#c89468', hair: '#8a5a2a' } },
    { proto: 'merchant', id: 'ar_mags', name: 'Mags', at: ap('petitioner'), dialog: 'ar_mags', team: 'neutral', barter: true, look: { female: true, skin: '#b07850', hair: '#5a3a20', hairStyle: 'bun', outfit: '#7a5a3a' },
      inv: [{ id: 'jerky', n: 6 }, { id: 'water', n: 4 }, { id: 'curePaste', n: 4 }, { id: 'ammo9', n: 30 }, { id: 'flare', n: 3 }, { id: 'scrip', n: 160 }] },
  ],
  onEnter: (c: Ctx, first: boolean) => {
    if (first) c.msg('A concrete bunker squats in the hillside behind a fence and a chicane of sandbags. Two armored figures stand before a barred blast gate with an open book welded into its centre. A few tents huddle around a campfire in the yard: petitioners, waiting.');
    if (c.flag('ar_admitted') || isInitiate(c)) {
      const o = c.obj('ar_blastDoor');
      if (o) o.locked = 0;
    }
    if (isInitiate(c)) {
      for (const id of ['ar_armoryDoor', 'ar_signalDoor']) {
        const o = c.obj(id);
        if (o) o.locked = 0;
      }
    }
    stockTomas(c);
  },
  onTick: (c: Ctx) => {
    if (G.combat || c.random(30) !== 0) return;
    const near = keepersWatching(7).filter((a) => a.npc !== 'ar_varga');
    if (!near.length) return;
    const a = near[c.random(near.length)];
    a._bark = { text: KEEPER_BARKS[c.random(KEEPER_BARKS.length)], until: G.now + 3500 };
  },
});

// --------------------------------------------------------------------- object scripts

defineObjScripts({
  ar_blastdoor: (c, o, _u, skill) => {
    if (o.open) return false;
    if (c.flag('ar_admitted') || isInitiate(c)) {
      o.locked = 0;
      return false;
    }
    if (skill === 'lockpick') {
      if (keepersWatching(10).length) {
        if (!c.flag('ar_pickWarned')) {
          c.set('ar_pickWarned');
          c.bark('ar_gate0', 'Step away from the door. Now.');
          c.msg('A Sentinel levels a laser carbine at your spine. There will not be a second warning.');
          return true;
        }
        c.set('ar_attacked');
        c.hostile('keepers');
        return true;
      }
      return false;
    }
    c.msg('The blast gate is a grille of steel bars on hydraulic rams. There is no handle or keyhole on this side. A Sentinel watches you touch it with polite, total hostility.');
    return true;
  },
  ar_guarded: (c, o, _u, skill) => {
    if (o.open) return false;
    if (isInitiate(c)) {
      o.locked = 0;
      return false;
    }
    if (skill === 'lockpick' && keepersWatching(8).length) {
      if (!c.flag('ar_innerWarned')) {
        c.set('ar_innerWarned');
        c.msg('"Outsider. Hands where I can see them." A Sentinel is watching you very closely.');
        return true;
      }
      c.set('ar_attacked');
      c.hostile('keepers');
      return true;
    }
    return false;
  },
  ar_aegisstand: (c) => {
    c.msg(c.flag('ar_aegisGiven') ? 'The Aegis Frame\'s stand is empty. The frame is with you now.' : 'An empty armor stand. Hedda says the Aegis Frame is kept in the Commander\'s own care, and only leaves it for someone she trusts with her life.');
    return true;
  },
  ar_lexicon: (c, _o, _u, skill) => {
    c.sound('terminal');
    if (skill === 'science' && !c.flag('ar_lexiconFixed')) {
      c.advance(30);
      if (c.roll('science', 30)) {
        c.set('ar_lexiconFixed');
        c.set('ar_impressed');
        c.xp(200);
        c.rep('archive', 10);
        c.msg('The Lexicon\'s index has been corrupted for years: every search for "water" returns a recipe for pickled eggs. You rebuild the hash table by hand. Somewhere behind you, Sister Ada makes a small, reverent noise.');
      } else c.msg('You dig into the Lexicon\'s index and make things, if anything, slightly worse. Sister Ada coughs meaningfully.');
      return true;
    }
    import('../ui/pda').then((p) => p.addNote('THE LEXICON - Archive index engine\nHoldings: 41,208 volumes; 3,117 spindles (1,902 readable).\nSelected entries: "HC-40 Aquifer Regulator: Holloway-Brandt, installed in public shelters 7, 12, 29." "Fort Kessler: Army Chemical Corps, crater district, project BLOOM (restricted)." "Harrow Observatory (southern cliffs): civil broadcast relay, glass dome."'));
    c.msg(c.flag('ar_lexiconFixed') ? 'The Lexicon answers every query briskly now. You download a few entries to your wrist-link.' : 'The Lexicon grinds through its index. Some of the results are even relevant. You download a few entries to your wrist-link.');
    return true;
  },
  ar_receiver: (c, _o, _u, skill) => {
    if (c.flag('ar_relayFixed')) {
      c.sound('terminal');
      c.msg('The receiver hisses. Under the static, a tone rises and falls, slow as breathing. Every hour, a burst of code: a callsign. S-H-E-P-H-E-R-D.');
      return true;
    }
    if (skill === 'repair' || skill === 'science') {
      if (skill === 'repair' && c.count('scrapElectronics') < 2) {
        c.msg('The receiver\'s front end is burnt out. You\'ll need at least two salvaged circuit boards to rebuild it. Brother Tomas might have some.');
        return true;
      }
      c.advance(90);
      const ok = skill === 'repair' ? c.roll('repair', 20) : c.roll('science', 40);
      if (ok) {
        if (skill === 'repair') c.take('scrapElectronics', 2);
        c.set('ar_relayFixed');
        c.xp(200);
        c.sound('terminal');
        c.msg(skill === 'repair'
          ? 'You pull the burnt boards, solder in salvaged ones, and re-seat the antenna feed. The receiver hisses to life, and under the static comes a tone, rising and falling, slow as breathing.'
          : 'The receiver isn\'t broken so much as detuned: its reference crystal has drifted. You recalibrate it against the generator hum. Under the static comes a tone, rising and falling, slow as breathing.');
        c.quest('ar_relay', 'The receiver works. The signal is back. Sister Ada or the Commander will want to hear it.');
      } else c.msg('An hour and a half of work, and the receiver produces nothing but a smell of hot dust. You\'ll have to try again.');
      return true;
    }
    c.msg('The long-range receiver: a cabinet of valves and dials wired to a trunk that climbs through the roof. It\'s dead. Someone with Repair (and spare circuit boards) or Science could bring it back.');
    return true;
  },
  ar_siglog: (c) => {
    c.sound('terminal');
    import('../ui/pda').then((p) => p.addNote('ARCHIVE SIGNAL LOG (excerpt)\nCarrier on 3.1 MHz, bearing SSW, source est. southern cliffs. Tone modulation, 0.2 Hz, "like breathing" (Ada).\nNote: Grafted sightings cluster within 4 days of modulation changes. Coincidence? (Varga: NO)\nReceiver failure, winter. Front end burnt. Parts requested.'));
    c.msg('The signal log. Someone has underlined "Coincidence? NO" three times.');
    return true;
  },
  ar_wsterm: (c) => {
    c.sound('terminal');
    c.msg('A cell-charging schedule, a list of borrowed tools (Dace: 14, all overdue), and a long, bitter memo about the price of copper.');
    return true;
  },
});

// --------------------------------------------------------------------- dialogue

const bye = { text: 'Goodbye.', end: true };

defineDialogues([
  {
    id: 'ar_gate',
    portrait: { bg: '#2e3036' },
    start: (c) => (c.flag('ar_admitted') || isInitiate(c) ? 'admitted' : c.flag('ar_metGate') ? 'again' : 'hello'),
    nodes: {
      hello: {
        onEnter: (c) => c.set('ar_metGate'),
        text: 'The Sentinel doesn\'t raise the laser carbine. He doesn\'t need to. His helmet is scratched with small, neat tally marks.\n\n"Halt. This is the Archive of the Keepers. Petitioners wait in the yard. Traders deal with Mags. Everyone else walks back the way they came. Which are you?"',
        options: [
          { text: 'I seek knowledge. I\'d like to speak with whoever is in charge.', to: 'knowledge' },
          { text: 'How does someone join the Keepers?', to: 'join' },
          { text: 'I carry a letter from the Warden of Shelter 29.', if: (c) => c.has('wardenLetter'), to: 'letter' },
          { text: 'I have a data spindle, from Calder.', if: (c) => c.has('dataSpindle'), to: 'spindle' },
          { text: 'I have the logs of Shelter 7. Grey giants took its people.', if: (c) => c.has('cr_s7logs'), to: 'logs' },
          { text: 'Your door\'s rams are whining. The seals on the left cylinder are going, and when they blow you\'ll be locked in, not out.', skill: { key: 'science', diff: 30 }, to: 'rams', fail: 'ramsNo' },
          { text: 'I\'ve walked a long way. Surely the Commander can spare a minute for a traveller.', skill: { key: 'speech', diff: 45 }, to: 'talked', fail: 'talkedNo' },
          { text: 'Me knock knock. Open door?', lowInt: true, to: 'dumb' },
          { text: 'Me have shiny stick!', lowInt: true, if: (c) => c.has('dataSpindle'), to: 'spindle' },
          bye,
        ],
      },
      again: {
        text: '"You again. The answer hasn\'t changed."',
        options: [
          { text: 'How does someone join?', to: 'join' },
          { text: 'I carry a letter from the Warden of Shelter 29.', if: (c) => c.has('wardenLetter'), to: 'letter' },
          { text: 'I have a data spindle.', if: (c) => c.has('dataSpindle'), to: 'spindle' },
          { text: 'I have the logs of Shelter 7.', if: (c) => c.has('cr_s7logs'), to: 'logs' },
          { text: 'Your door\'s rams are whining. The left cylinder\'s seals are going.', skill: { key: 'science', diff: 30 }, if: (c) => !c.flag('ar_ramsTried'), do: (c) => c.set('ar_ramsTried'), to: 'rams', fail: 'ramsNo' },
          { text: 'Me knock knock again.', lowInt: true, to: 'dumb' },
          { text: 'Me have shiny stick!', lowInt: true, if: (c) => c.has('dataSpindle'), to: 'spindle' },
          bye,
        ],
      },
      knowledge: {
        text: '"Everyone seeks knowledge. Mostly the knowledge of where we keep the rifles." He doesn\'t move. "The Commander does not receive petitioners. The Commander receives initiates, and those who bring the Archive something worth keeping."',
        options: [{ text: 'How does someone become an initiate?', to: 'join' }, bye],
      },
      join: {
        onEnter: (c) => {
          if (c.questState('ar_trial') === 'none') c.quest('ar_trial', 'The Sentinel at the Archive gate says petitioners must bring a pre-war data spindle to be heard. There is a vault of them in the Calder technical library annex, south-east of the transit station.');
          c.reveal('calder');
        },
        text: '"The Trial. Bring the Archive a pre-war data spindle, intact. There is a vault of them in the technical library annex in Calder, south-east of the old transit station." A pause. "It sits in a radiation hotspot, and Hollow Ones nest in the stacks. Two of ours went last year. Neither came back. Bring a spindle and the door will open for you."',
        options: [
          { text: 'I\'ll bring one.', end: true },
          { text: 'Why not go back for it yourselves?', to: 'why' },
        ],
      },
      why: {
        text: '"Because the Commander decided that the Archive has lost enough Sentinels to that building. And because a petitioner who comes back from it is worth more than one who talks well at the gate."',
        options: [{ text: 'Fair enough.', end: true }],
      },
      letter: {
        onEnter: (c) => admit(c, 'letter'),
        text: 'He reads the Warden\'s letter twice, then looks at your jumpsuit, then at the letter again. "A sealed shelter. Still sealed, until you." Something shifts behind the visor. "The Commander will want to see you. She has a standing order about shelter folk."\n\nHe raps on the bars. Somewhere inside, rams groan, and the blast gate grinds open.',
        options: [{ text: 'Thank you.', end: true }],
      },
      spindle: {
        onEnter: (c) => admit(c, 'spindle'),
        text: '"Show me." He turns the spindle in his gauntlet and a thread of light runs through the glass. "Vault B." He looks at you differently. "Inside. The Commander is in the Hall of Record, straight ahead."\n\nThe blast gate grinds open.',
        options: [{ text: 'Thanks.', end: true }, { text: 'Yay! Door open!', lowInt: true, end: true }],
      },
      logs: {
        onEnter: (c) => admit(c, 'logs'),
        text: '"Shelter 7." He is silent for a moment. "We spoke to them, over the old intercom line. Their Warden turned us down." He hands the tape back. "The Commander will want to hear this herself. Inside."\n\nThe blast gate grinds open.',
        options: [{ text: 'Thank you.', end: true }],
      },
      rams: {
        onEnter: (c) => { c.set('ar_impressed'); admit(c, 'science'); },
        text: 'The Sentinel tilts his head, listening. The left ram is, now that you mention it, whining. He keys his radio. "Tomas. The outsider says the left cylinder seals are going." A crackle, a long pause, a crackle. "...He says you\'re right, and he wants to know who you are." The Sentinel steps aside. "So does the Commander. Inside."',
        options: [{ text: 'Thank you.', end: true }],
      },
      ramsNo: {
        text: '"The door is fine," he says. "The door has been fine for eighty-six years."',
        options: [bye],
      },
      talked: {
        onEnter: (c) => admit(c, 'speech'),
        text: 'The Sentinel regards you for a long moment. Then he sighs, and it sounds almost human. "Eleven years I\'ve stood here, and nobody has asked nicely." He keys his radio and mutters. "One visitor. Hall of Record only. Touch nothing."\n\nThe blast gate grinds open.',
        options: [{ text: 'Thank you.', end: true }],
      },
      talkedNo: {
        text: '"The Commander spares minutes for initiates. Walk on, traveller."',
        options: [{ text: 'How does someone become an initiate?', to: 'join' }, bye],
      },
      dumb: {
        onEnter: (c) => {
          if (c.questState('ar_trial') === 'none') c.quest('ar_trial', 'Metal man says: bring shiny glass stick from library in Calder (ruined city, south-east). Then door opens.');
          c.reveal('calder');
        },
        text: 'The Sentinel looks at you for a long time. Then, slowly and clearly: "No. Door does not open for knock knock." He holds up a thumb and finger a few inches apart. "Door opens for a glass stick. A spindle. Old library, in Calder. The broken city. That way." He points south. "Bring stick. Door opens."',
        options: [{ text: 'Get stick. Door open. Okay!', lowInt: true, end: true }],
      },
      admitted: {
        text: (c) => (isInitiate(c) ? '"Initiate." A nod, fractionally deeper than the one he gives anyone else.' : '"The Commander is in the Hall of Record. Touch nothing."'),
        options: [{ text: 'Thanks.', end: true }],
      },
    },
  },
  {
    id: 'ar_varga',
    portrait: { bg: '#2a2a30' },
    start: (c) => {
      if (!c.flag('ar_metVarga')) return 'hello';
      if (c.has('dataSpindle') && !isInitiate(c)) return 'spindle';
      if (c.flag('ar_relayFixed') && c.questState('ar_relay') === 'active' && (c.flag('ar_hymnDecoded') || c.flag('dead:ar_ada'))) return 'relayDone';
      return 'again';
    },
    nodes: {
      hello: {
        onEnter: (c) => c.set('ar_metVarga'),
        text: 'Scribe-Commander Odile Varga does not rise. She is perhaps sixty, iron-grey hair pinned in a severe knot, a laser pistol on the table beside a stack of index cards, as if the two were equally dangerous.\n\n"The Sentinels tell me you got through a door that has been closed to petitioners for eleven years. Sit. Explain yourself briefly. I have forty thousand pages to catalogue before I die, and I intend to die on schedule."',
        options: [
          { text: 'I\'m from Shelter 29. We need a hydro-core, or my people die of thirst.', to: 'shelter' },
          { text: 'Who are the Keepers?', to: 'keepers' },
          { text: 'I want to join.', to: 'join' },
          { text: 'I brought a spindle.', if: (c) => c.has('dataSpindle'), to: 'spindle' },
          { text: 'That index engine behind you: the drive bay\'s been re-seated by hand. Recently. Badly.', skill: { key: 'science', diff: 35 }, if: (c) => !c.flag('ar_vargaSci'), do: (c) => c.set('ar_vargaSci'), to: 'sci', fail: 'sciNo' },
          { text: 'Me want shiny gun.', lowInt: true, to: 'dumb' },
          bye,
        ],
      },
      keepers: {
        text: '"When the bombs fell, a company of army signals engineers was sheltering here with a library they\'d been ordered to evacuate. They decided the order was still in force. We are that evacuation, still underway."\n\n"We keep what the world forgot: how to charge a cell, how to set a bone, how a reactor breathes. We do not hand it out to people who would use it to kill each other faster. Which, historically, is everyone."',
        options: [
          { text: 'How do I join?', to: 'join' },
          { text: 'I need your help. My shelter is dying of thirst.', to: 'shelter' },
          bye,
        ],
      },
      shelter: {
        onEnter: (c) => c.reveal('calder'),
        text: (c) => `"A sealed shelter." For the first time she looks at you properly. "Holloway-Brandt built four in this basin. Seven, twelve, twenty-nine, and forty, which was never finished. Your core is an HC-40. There was a spare installed at Shelter 7, under the Calder transit station. I have marked it." She taps an index card. "${c.flag('shelter7Logs') ? 'Though you have been there already, I think.' : 'You will find the Withered there, and a sect called the Sealed who will not let you near the door.'}"`,
        options: [
          { text: 'Thank you, Commander.', to: 'again' },
        ],
      },
      join: {
        onEnter: (c) => {
          if (c.questState('ar_trial') === 'none') c.quest('ar_trial', 'Scribe-Commander Varga will make me an initiate if I bring a pre-war data spindle from the Calder technical library annex, south-east of the transit station.');
          c.reveal('calder');
        },
        text: '"Everyone wants to join when they see the rifles. The rifles are the least of it." She squares her index cards. "The Trial is simple. Bring the Archive a pre-war data spindle, intact. There is a vault of them in the Calder technical library annex, south-east of the transit station. It sits in a radiation hotspot, and Hollow Ones nest in the stacks. Two of my people died there last year."',
        options: [
          { text: 'What do initiates get?', to: 'perks' },
          { text: 'I\'ll bring you one.', end: true },
        ],
      },
      perks: {
        text: '"Access to the armory, and to the better half of Brother Tomas\'s stock. The records, within reason. A bunk. And eventually, a voice in what we do with what we know." A thin smile. "That last one is the rarest thing in the Basin."',
        options: [{ text: 'I\'ll bring you a spindle.', end: true }],
      },
      sci: {
        onEnter: (c) => { c.set('ar_impressed'); c.xp(100); },
        text: 'Varga raises an eyebrow by perhaps a millimetre. "Re-seated by hand, yes. By me, with a butter knife, in a winter I would rather forget." She writes something on an index card. "Sister Ada will want to meet you. Tell her I said the library may speak to you."',
        options: [
          { text: 'I\'d like to join.', to: 'join' },
          { text: 'Thank you.', to: 'again' },
        ],
      },
      sciNo: {
        text: '"It is a filing cabinet," she says flatly. It is not a filing cabinet.',
        options: [{ text: 'Of course.', to: 'again' }],
      },
      dumb: {
        onEnter: (c) => {
          if (c.questState('ar_trial') === 'none') c.quest('ar_trial', 'Boss lady says: bring glass stick from library in Calder (broken city, south-east). Then get shiny gun.');
          c.reveal('calder');
        },
        text: 'Varga studies you for a long moment. Then she holds up a thumb-length rod of glass and steel from her desk, and speaks very clearly.\n\n"Shiny guns are for Keepers. To be a Keeper, bring me one of these. From the library in Calder. The broken city." She points south. "Watch out for the biting people. Go."',
        options: [{ text: 'Get stick! Get gun!', lowInt: true, end: true }],
      },
      spindle: {
        text: 'You set the spindle on her table. Varga holds it to the lamp and turns it slowly; a thread of light runs down the glass. "Calder Municipal Technical, Vault B. Intact." She puts it down with more gentleness than you would have guessed she owned.\n\n"The Trial is passed. Kneel, or don\'t. We gave up on ceremony when the last ceremonial sword broke."',
        options: [
          { text: 'Thank you, Commander.', do: (c) => initiate(c), to: 'initiated' },
          { text: 'Me Keeper now?', lowInt: true, do: (c) => initiate(c), to: 'initiatedDumb' },
        ],
      },
      initiated: {
        text: '"This is your signet. It opens the armory and the signal room. Brother Tomas will sell you what outsiders never see, and Hedda in the armory will issue you a kit. Sister Ada will answer your questions. Most of them." She pauses. "And there is something I need done, that my own people have failed at twice."',
        options: [
          { text: 'What is it?', to: 'relayOffer' },
          { text: 'Later.', end: true },
        ],
      },
      initiatedDumb: {
        text: '"Yes. Keeper now." She presses a steel ring into your hand. "This opens doors. Hedda gives you a gun. Try not to point it at the books." She seems, almost, to be enjoying herself.',
        options: [{ text: 'Shiny gun! Thanks boss!', lowInt: true, end: true }],
      },
      relayOffer: {
        onEnter: (c) => { if (c.questState('ar_relay') === 'none') c.quest('ar_relay', 'Varga wants the long-range receiver in the signal room (north of the Hall of Record) repaired: Repair with two salvaged circuit boards, or Science. Her reward: the Aegis Frame.'); },
        text: '"Our long-range receiver died two winters ago. Before it did, it was listening to a carrier from the south: a tone, rising and falling, slow as breathing. Every Grafted sighting in our records falls within days of that tone changing pitch."\n\n"I want it heard again. The receiver is in the signal room, behind this hall. Tomas has parts. Get it working and I will give you the one thing in this bunker I value more than the books: the Aegis Frame."',
        options: [{ text: 'I\'ll see what I can do.', end: true }],
      },
      relayDone: {
        onEnter: (c) => {
          c.questDone('ar_relay', 'The receiver works, and the signal from the south has been traced. Varga gave me the Aegis Frame.');
          c.set('ar_aegisGiven');
          c.give('aegisPlate');
          c.rep('archive', 20);
          reveal(c, 'cathedral', 'The Keepers traced a control signal, "the Hymn", to the Glass Cathedral on the southern cliffs.');
        },
        text: '"Ada tells me the tone is coming from the southern cliffs. The old Harrow Observatory, which the pilgrims now call the Glass Cathedral." Varga is standing, which you have not seen before. "Something there is singing to the Grafted, and they listen. And it signs its songs: Shepherd."\n\nShe takes a key from her collar and unlocks a long steel case under the table. Inside, folded like a sleeping insect, is a suit of articulated plate. "The Aegis Frame. The last of its kind that still works. You will need it more than I will."',
        options: [
          { text: 'I\'ll put it to good use.', end: true },
          { text: 'Shiny! Big shiny!', lowInt: true, end: true },
        ],
      },
      again: {
        text: (c) => (isInitiate(c) ? '"Initiate. Speak."' : '"Speak. Briefly."'),
        options: [
          { text: 'About the Trial...', if: (c) => c.questState('ar_trial') === 'active', to: 'join' },
          { text: 'About the receiver...', if: (c) => c.questState('ar_relay') === 'active', to: 'relayStatus' },
          { text: 'What do you know about the Grafted?', if: (c) => isInitiate(c), to: 'grafted' },
          { text: 'People are being taken by grey giants. If you know anything, share it.', if: (c) => !isInitiate(c) && (c.flag('act2') || c.flag('shelter7Logs')) && !c.flag('ar_toldKessler'), skill: { key: 'speech', diff: 40 }, to: 'grafted', fail: 'noShare' },
          { text: 'Read this. Shelter 7\'s last log.', if: (c) => c.has('cr_s7logs') && !c.flag('ar_logsShown'), to: 'logs' },
          { text: 'The Grafted must be stopped. Will the Keepers fight?', if: (c) => canPledge(c), to: 'pledge' },
          { text: 'There\'s a boy outside, Farrow. I\'ll vouch for him.', if: (c) => isInitiate(c) && c.questState('ar_farrow') === 'active', to: 'farrow' },
          { text: 'Hello boss lady.', lowInt: true, to: 'dumbAgain' },
          { text: 'Keepers fight big grey men? With me?', lowInt: true, if: (c) => canPledge(c) && !!c.flag('ar_relayFixed'), to: 'pledged' },
          bye,
        ],
      },
      dumbAgain: {
        text: (c) => (isInitiate(c) ? '"Initiate." She almost smiles. "Go and see Tomas. He likes you. Heaven knows why."' : '"The spindle. From Calder. Go."'),
        options: [{ text: 'Okay!', lowInt: true, end: true }],
      },
      relayStatus: {
        text: (c) => (c.flag('ar_relayFixed') ? '"Ada is listening now. Go and ask her what she hears."' : '"The receiver is in the signal room, behind this hall. Your signet opens it. Tomas has circuit boards if you need them."'),
        options: [{ text: 'Understood.', end: true }],
      },
      grafted: {
        onEnter: (c) => reveal(c, 'kessler', 'The Keepers say the Grafted are made at Fort Kessler, a pre-war army base in the crater country north-east of the Archive, in something called project Bloom.'),
        text: '"They are made, not born. Our pre-war procurement files mention a mutagen programme run by the army chemical corps at Fort Kessler, north-east of here, in the crater country. The files call it Bloom." She slides an index card across the table; the location is written on it in tiny, perfect capitals. "Our patrols have seen grey giants marching captives in that direction. None of the captives came back."',
        options: [
          { text: 'And who commands them?', to: 'commands' },
          { text: 'Thank you.', to: 'again' },
        ],
      },
      commands: {
        onEnter: (c) => {
          if (c.flag('act2') || c.flag('shelter7Logs') || c.flag('ar_relayFixed')) reveal(c, 'cathedral', 'The Keepers suspect the Grafted obey a broadcast from the Glass Cathedral, the old observatory on the southern cliffs.');
        },
        text: (c) => (c.flag('act2') || c.flag('shelter7Logs') || c.flag('ar_relayFixed')
          ? '"Brutes that size do not organise themselves. Our receiver heard a carrier from the south, before it died: from the cliffs, where the old Harrow Observatory stands. The pilgrims call it the Glass Cathedral now, and sing hymns there." She taps the card. "I do not believe in coincidences. I believe in bearings. Go and look, if you must. Carefully."'
          : '"I have a suspicion, and I do not share suspicions with people who have not seen the Grafted with their own eyes. Come back when you have."'),
        options: [{ text: 'Thank you, Commander.', to: 'again' }],
      },
      noShare: {
        text: '"The Archive shares with initiates. That is not cruelty; it is the only way we have survived eighty-six years of people who wanted what we know." She returns to her cards. "Pass the Trial."',
        options: [bye],
      },
      logs: {
        onEnter: (c) => {
          c.set('ar_logsShown');
          c.xp(200);
          c.rep('archive', 10);
          reveal(c, 'kessler', 'Commander Varga matched Shelter 7\'s log to the Keepers\' files: the Grafted come from Fort Kessler, in the crater country north-east of the Archive.');
        },
        text: 'Varga reads the log once quickly, and once slowly. At "pure stock" her jaw tightens. At "the Shepherd" she reaches for a clean index card, writes SHEPHERD at the top, and underlines it twice.\n\n"Warden Ashby. He turned us down, you know. Over the intercom. Very politely." She is quiet. "Collars, a tone on the radio, and a taste for shelter folk. The collars are army issue: Fort Kessler, in the crater country. I have marked it for you."',
        options: [
          { text: 'And the Shepherd?', to: 'commands' },
          { text: 'Thank you.', to: 'again' },
        ],
      },
      pledge: {
        text: '"Fight." She sets down her pen. "The Archive has survived eighty-six years by not fighting other people\'s wars. Convince me this one is ours."',
        options: [
          { text: 'You heard the Hymn yourself. It is coming for everything you keep. Help me silence it.', if: (c) => !!c.flag('ar_relayFixed'), to: 'pledged' },
          { text: 'They\'re taking shelter folk because we\'re "pure". When the shelters are empty, they\'ll come for everyone else. Books don\'t survive the people who read them.', skill: { key: 'speech', diff: 40 }, to: 'pledged', fail: 'pledgeNo' },
          { text: 'Never mind.', to: 'again' },
        ],
      },
      pledged: {
        onEnter: (c) => {
          c.set('ar_pledged');
          c.karma(10);
          c.xp(300);
          if (c.questState('grafted') === 'active') c.quest('grafted', 'Scribe-Commander Varga has pledged a squad of Keeper Sentinels to the fight against the Grafted.');
        },
        text: '"The Archive was built to outlast the end of the world," Varga says. "It seems the world insists on ending again." She stands, and every Sentinel in the hall straightens.\n\n"When you move against the fort or the Cathedral, the Keepers will be there. Twelve Sentinels. It is every rifle I can spare, and three I can\'t."',
        options: [{ text: 'Thank you, Commander.', end: true }, { text: 'Yay! Friends!', lowInt: true, end: true }],
      },
      pledgeNo: {
        text: '"Rhetoric. I have eighty shelves of it." She picks up her pen again. "Bring me something better than rhetoric."',
        options: [bye],
      },
      farrow: {
        onEnter: (c) => {
          c.set('ar_farrowVouched');
          c.questDone('ar_farrow', 'I vouched for Farrow, and the Keepers took him in as an initiate.');
          c.karma(10);
        },
        text: '"The boy who has been sitting in my yard for eleven days." She sighs. "He went to Calder, you know. Got as far as the yellow signs, and came back ashamed." A pause. "Courage and shame in the right proportions. Very well. On your word, initiate. If he burns down the library, I shall hold you responsible."',
        options: [{ text: 'He won\'t.', end: true }],
      },
    },
  },
  {
    id: 'ar_ada',
    portrait: { bg: '#3a3028' },
    start: (c) => (c.flag('ar_metAda') ? 'again' : 'hello'),
    nodes: {
      hello: {
        onEnter: (c) => c.set('ar_metAda'),
        text: 'Sister Ada is small, quick, and ink-stained to the elbows. She looks up from a book whose spine she is re-sewing with fishing line.\n\n"Oh! A visitor! We don\'t get... are you allowed in here? Never mind, you\'re in here. That\'s practically the same thing. Mind the stacks, some of those volumes are held together by optimism."',
        options: [
          { text: 'What is this place?', to: 'library' },
          { text: 'Do you know anything about hydro-cores?', to: 'cores' },
          { text: 'Many books! You read all?', lowInt: true, to: 'dumb' },
          bye,
        ],
      },
      again: {
        text: (c) => (knowsSecrets(c) ? '"Back again! Ask me anything. Well. Almost anything."' : '"Hello again. The Commander decides what I may tell outsiders, I\'m afraid, and she\'s decided \'very little\'."'),
        options: [
          { text: 'What is this place?', to: 'library' },
          { text: 'Do you know anything about hydro-cores?', to: 'cores' },
          { text: 'What do you know about the Grafted?', if: (c) => knowsSecrets(c) && (c.flag('act2') || c.flag('shelter7Logs') || isInitiate(c)), to: 'grafted' },
          { text: 'Tell me about the signal from the south.', if: (c) => knowsSecrets(c) && !c.flag('ar_relayFixed'), to: 'signal' },
          { text: 'The receiver is working. What do you hear?', if: (c) => !!c.flag('ar_relayFixed') && !c.flag('ar_hymnDecoded'), to: 'hymn' },
          { text: 'Can I help with the Lexicon?', if: (c) => !c.flag('ar_lexiconFixed'), to: 'lexicon' },
          { text: 'Many books! You read all?', lowInt: true, to: 'dumb' },
          bye,
        ],
      },
      library: {
        text: '"The stacks! Forty-one thousand volumes, three thousand spindles, and one index engine, the Lexicon, that thinks every question is about pickled eggs." She beams. "Engineering, medicine, agronomy, a complete run of a magazine about model railways that I will defend with my life. The Keepers were soldiers once. Now we\'re mostly librarians with very good guns."',
        options: [{ text: 'Thanks.', to: 'again' }],
      },
      cores: {
        onEnter: (c) => c.reveal('calder'),
        text: '"HC-40! Holloway-Brandt aquifer regulators. Lovely engineering. The membranes last about a century, which, um." She winces. "Which is about now. Shelter 7, under Calder, was listed with a spare in its cradle. If anyone could still reach it, it would be there."',
        options: [{ text: 'Thanks, Ada.', to: 'again' }],
      },
      grafted: {
        onEnter: (c) => reveal(c, 'kessler', 'Sister Ada found pre-war files on project Bloom at Fort Kessler, in the crater country north-east of the Archive: the likely source of the Grafted.'),
        text: '"I\'ve been cross-referencing." She pulls a folder from under a stack. "Army Chemical Corps, Fort Kessler, crater district. Project BLOOM: \'accelerated somatic adaptation for irradiated environments\'. The files are mostly redactions, but the requisitions aren\'t: vats, restraint collars, and a truly obscene quantity of growth medium." She looks ill. "Somebody finished the project. I\'ve marked the fort for you."',
        options: [{ text: 'Thank you, Ada.', to: 'again' }],
      },
      signal: {
        onEnter: (c) => {
          if (c.flag('act2') || c.flag('shelter7Logs')) reveal(c, 'cathedral', 'Sister Ada suspects the tone the Grafted listen to comes from the Glass Cathedral on the southern cliffs.');
        },
        text: (c) => (c.flag('act2') || c.flag('shelter7Logs')
          ? '"Before the receiver died, we were logging a carrier from the south-south-west. A tone, going up and down, like somebody breathing in their sleep." She shivers. "The bearing points at the southern cliffs, at the old observatory. The Glass Cathedral, the pilgrims call it. If the Grafted are listening to something, I\'d bet my model railways it comes from there. I\'ve marked it. If we could get the receiver working again, we\'d know for sure."'
          : '"Before the receiver died, we were logging a carrier from the south. A tone, going up and down, like breathing. The Commander thinks it matters. I think it\'s creepy. If we could get the receiver working again, we\'d know more."'),
        options: [{ text: 'Thanks, Ada.', to: 'again' }],
      },
      hymn: {
        onEnter: (c) => {
          c.set('ar_hymnDecoded');
          reveal(c, 'cathedral', 'The Keepers\' receiver traced the Hymn, the tone the Grafted obey, to the Glass Cathedral on the southern cliffs. It carries a callsign: SHEPHERD.');
        },
        text: 'Ada has headphones clamped over her ears and three pages of notes. She holds up a finger, listens, writes.\n\n"It\'s not music. It\'s a control carrier: the tone shifts, and the pattern of shifts repeats, like words. Instructions." She taps a page. "It comes from the Harrow Observatory, the Glass Cathedral, on the southern cliffs, dead on the bearing. And once an hour it signs itself: SHEPHERD." She takes the headphones off. "I\'m going to tell the Commander. And then I\'m going to sit down for a while."',
        options: [{ text: 'Tell her.', end: true }],
      },
      lexicon: {
        text: '"Would you? The index is corrupted. Every query about water returns a recipe for pickled eggs. I\'ve been rebuilding it by hand, one card at a time." She waves at the terminal. "If you know the insides of these things, be my guest."',
        options: [{ text: 'I\'ll have a look. [use Science on the Lexicon]', end: true }],
      },
      dumb: {
        text: '"All of them? Oh, goodness, no. Only about nine thousand." She pulls a picture book from a shelf: *Trains of the World*. "Here. Sit. I\'ll read you this one; it\'s my favourite." And she does, doing all the whistle noises.\n\nAfterwards, she adds, "If you want to be a Keeper, bring the Commander a spindle. A glass stick. From Calder. Watch out for the Hollow Ones, they bite."',
        options: [{ text: 'Choo choo!', lowInt: true, end: true, do: (c) => { c.reveal('calder'); if (c.questState('ar_trial') === 'none') c.quest('ar_trial', 'Ada says: bring glass stick from Calder to boss lady.'); } }],
      },
    },
  },
  {
    id: 'ar_tomas',
    portrait: { bg: '#3a2e26' },
    start: 'hello',
    nodes: {
      hello: {
        text: (c) => (isInitiate(c)
          ? 'Brother Tomas pushes his jeweller\'s loupe up onto his forehead. "Initiate! The back room\'s open to you now. Carbines, composite, cells by the crate. Don\'t tell the Commander what I charge her own people."'
          : 'Brother Tomas is broad, burn-scarred to the elbows, and has a jeweller\'s loupe pushed up on his forehead. "Outsider stock\'s on the front bench. The good stuff\'s in the back, and you\'re not seeing it till the Commander says so."'),
        options: [
          { text: 'Let\'s trade.', barter: true, any: true },
          { text: 'What do you make here?', to: 'make' },
          { text: 'I need parts for the receiver.', if: (c) => c.questState('ar_relay') === 'active' && !c.flag('ar_tomasParts') && !c.flag('ar_relayFixed'), to: 'parts' },
          { text: 'Me buy laser!', lowInt: true, barter: true },
          bye,
        ],
      },
      make: {
        text: '"Cells, mostly. Recharge them, rebuild them, curse at them. We\'ve got the only working charging bank I know of in the Basin." He pats a humming cabinet. "Laser weapons are simple, once you\'ve got the cells and the crystals. We\'ve got the cells. The crystals I grow in a jar, very slowly, and swear at."',
        options: [{ text: 'Let\'s trade.', barter: true }, { text: 'Thanks.', end: true }],
      },
      parts: {
        onEnter: (c) => { c.set('ar_tomasParts'); c.give('scrapElectronics', 2); },
        text: '"The receiver! Finally someone\'s going to look at it who isn\'t Dace." He digs two blackened circuit boards out of a drawer. "Salvage. They\'ll do for the front end. Solder\'s on the bench. If it catches fire, it was already broken."',
        options: [{ text: 'Thanks, Tomas.', end: true }],
      },
    },
  },
  {
    id: 'ar_hedda',
    start: 'hello',
    nodes: {
      hello: {
        text: (c) => (isInitiate(c)
          ? (c.flag('ar_kit') ? '"Keep that carbine clean, initiate. I check."' : '"New initiate. Good. You\'re owed a kit." Armorer Hedda Kray looks you up and down like a tailor with a grudge.')
          : '"Outsider. In my armory." Hedda Kray\'s hand rests on her holster. "Explain yourself quickly."'),
        options: [
          { text: 'I\'ll take that kit.', if: (c) => isInitiate(c) && !c.flag('ar_kit'), to: 'kit' },
          { text: 'Gun please!', lowInt: true, if: (c) => isInitiate(c) && !c.flag('ar_kit'), to: 'kit' },
          { text: 'Leaving.', end: true },
        ],
      },
      kit: {
        onEnter: (c) => { c.set('ar_kit'); c.give('laserPistol'); c.give('cell', 40); c.give('hypo', 1); },
        text: '"One laser pistol, forty cells, one mend-hypo. Sign here." She thrusts a ledger at you. "Lose the pistol and you buy the next one from Tomas at his prices. You don\'t want Tomas\'s prices."',
        options: [{ text: 'Thanks, Hedda.', end: true }],
      },
    },
  },
  {
    id: 'ar_sentinel',
    start: 'hello',
    nodes: {
      hello: {
        text: (c) => (isInitiate(c)
          ? ['"Initiate."', '"The Commander\'s in a mood. Well. The Commander\'s in her usual mood."', '"Cells don\'t grow on trees. Ask Tomas; he\'s tried."'][c.random(3)]
          : ['"Touch nothing."', '"Outsiders keep to the Hall of Record."', '"I\'m watching you. It\'s not personal. I watch everyone."'][c.random(3)]),
        options: [{ text: 'Goodbye.', end: true }],
      },
    },
  },
  {
    id: 'ar_linnet',
    start: 'hello',
    nodes: {
      hello: {
        text: 'Scribe Linnet has a clipboard and the expression of someone who has been told to "handle visitors" and never been told how.\n\n"Welcome to the Hall of Record. The Commander receives at the table. The library is west, the workshop east, barracks and armory south of the vestibule, and the signal room is behind the Commander and none of your business."',
        options: [
          { text: 'What\'s the signal room?', to: 'signal' },
          { text: 'Thanks.', end: true },
        ],
      },
      signal: {
        text: '"None of your business," she repeats, with a little more confidence the second time.',
        options: [{ text: 'Fair enough.', end: true }],
      },
    },
  },
  {
    id: 'ar_hollis',
    start: 'hello',
    nodes: {
      hello: {
        text: 'Scribe Hollis is copying a water-damaged page by lamplight, lips moving. "Pre-war dentistry," he says without looking up. "Did you know they used to fill teeth with silver? Silver! In their mouths!" He seems personally offended.',
        options: [{ text: 'Fascinating.', end: true }],
      },
    },
  },
  {
    id: 'ar_dace',
    start: 'hello',
    nodes: {
      hello: {
        text: 'Apprentice Dace is holding two wires apart with the concentration of someone who has learned the hard way what happens when they touch. "Don\'t startle me. Please. Last time I startled, we lost the east lamps for a week."',
        options: [
          { text: 'What happened to the receiver?', to: 'receiver' },
          { text: 'Good luck.', end: true },
        ],
      },
      receiver: {
        text: '"...That might also have been me." He winces. "The front end burnt out during a storm. I tried to fix it. Then Brother Tomas said I\'m not allowed to fix things that are older than me any more. Which is all of them."',
        options: [{ text: 'Bad luck.', end: true }],
      },
    },
  },
  {
    id: 'ar_rook',
    start: 'hello',
    nodes: {
      hello: {
        text: '"Initiate Rook. Six months in." He grins. "The Trial took me three tries. First time I fell in a hole. Second time a Hollow One chewed my boot off. Third time I found a spindle in a dead scribe\'s pack, which I\'m told counts, but nobody\'s proud of it."',
        options: [
          { text: 'Any advice for the Calder annex?', to: 'advice' },
          { text: 'Good for you.', end: true },
        ],
      },
      advice: {
        text: '"Take rad-purge, and go fast. The spindle vault\'s in the back room of the reading room: a steel safe, simple lock. The Hollow Ones sleep in the stacks. Don\'t wake the big one." He thinks. "Or do, and shoot it. That also works."',
        options: [{ text: 'Thanks.', end: true }],
      },
    },
  },
  {
    id: 'ar_farrow',
    start: (c) => (c.flag('ar_farrowVouched') ? 'inside' : 'hello'),
    nodes: {
      hello: {
        text: 'A gangly boy of maybe fifteen sits by the petitioners\' fire, polishing a pair of boots that are not worth polishing.\n\n"Eleven days I\'ve been waiting. They say the Trial\'s a spindle from the library in Calder." He looks at his boots. "I went. I got as far as the yellow signs, and I heard the Hollow Ones, and I came back." A pause. "Don\'t tell anyone."',
        options: [
          { text: 'Why do you want to join so badly?', to: 'why' },
          { text: 'If I become an initiate, I\'ll put in a word for you.', if: (c) => c.questState('ar_farrow') === 'none', to: 'promise' },
          { text: 'You sad?', lowInt: true, to: 'why' },
          bye,
        ],
      },
      why: {
        text: '"My mum could read. She taught me on seed catalogues, it\'s all we had. She said the Keepers had a room full of books as big as a barn." He shrugs. "She died of a fever that a book probably knew how to fix. So."',
        options: [
          { text: 'If I become an initiate, I\'ll put in a word for you.', if: (c) => c.questState('ar_farrow') === 'none', to: 'promise' },
          { text: 'I\'m sorry.', end: true },
        ],
      },
      promise: {
        onEnter: (c) => c.quest('ar_farrow', 'Farrow, a boy camped outside the Archive, wants to join the Keepers. If I become an initiate, I can vouch for him to Commander Varga.'),
        text: '"You would?" He sits up so fast he drops a boot. "I\'ll... I\'ll be the best initiate they ever had. I\'ll even learn the dentistry stuff."',
        options: [{ text: 'We\'ll see.', end: true }],
      },
      inside: {
        text: 'Initiate Farrow is wearing a grey coat two sizes too big and the biggest smile in the Basin. "They let me into the library. Nine thousand books. Ada says I can read all of them if I start now and never sleep." He grabs your hand. "Thank you."',
        options: [{ text: 'Read one for me.', end: true }],
      },
    },
  },
  {
    id: 'ar_mags',
    start: 'hello',
    nodes: {
      hello: {
        text: 'Mags sells from the back of a wagon parked just outside the sandbags, as close to the door as the Sentinels let anyone get. "Tin-suited hoarders," she says cheerfully, nodding at the bunker. "They\'ve a whole room of medicine in there and they sell it by the thimble. So I sell to the people waiting outside. Somebody\'s got to."',
        options: [
          { text: 'Let\'s trade.', barter: true, any: true },
          { text: 'How do people get inside?', to: 'inside' },
          { text: 'Me buy food!', lowInt: true, barter: true },
          bye,
        ],
      },
      inside: {
        text: '"Bring them something old and clever. A spindle, they like: glass sticks with pre-war words in them. Or get lucky with the sentries; one of them is soft, underneath all that plate. Oh, and they love anything about the old shelters. Anything." She gives you a look. "Nice jumpsuit."',
        options: [{ text: 'Thanks, Mags.', end: true }],
      },
    },
  },
]);

// --------------------------------------------------------------------- endings

defineEndings([
  {
    order: 60,
    title: 'The Archive',
    scene: 'years',
    text: (c) => {
      const parts: string[] = [];
      if (c.flag('dead:ar_varga') || c.flag('ar_attacked') || c.flag('hostile:archive:keepers')) {
        parts.push(c.flag('dead:ar_varga')
          ? 'With Scribe-Commander Varga dead, the Keepers sealed their blast door and never opened it again. What they knew died with them, one volume at a time.'
          : 'After the stranger turned on them, the Keepers of the Archive sealed their blast door for good. Petitioners camped in the yard for years, and then stopped coming.');
        return parts.join(' ');
      }
      if (c.flag('ar_pledged') && c.flag('gameWon')) parts.push('Twelve Keeper Sentinels marched against the Grafted, and nine came home. Commander Varga wrote the account herself, and filed it under "history, recent, regrettably necessary".');
      else if (c.flag('ar_pledged')) parts.push('The Keepers kept their pledge and marched out of the Archive for the first time in a generation. The Basin had never seen laser fire in daylight before.');
      if (c.flag('ar_initiate')) parts.push('In time the Keepers opened a reading room in their yard, one day a week, for anyone who could sit still. They said an initiate from Shelter 29 had taught them that knowledge kept too long goes stale, like water.');
      else parts.push('The Keepers of the Archive kept their doors shut and their books dry, and the Basin went on without them, as it always had.');
      if (c.flag('ar_hymnDecoded')) parts.push('Sister Ada\'s recordings of the Hymn were studied for decades; she refused to let anyone play them aloud.');
      if (c.flag('ar_farrowVouched')) parts.push('Initiate Farrow became the Archive\'s librarian after Ada. He never did finish the dentistry section.');
      return parts.join(' ');
    },
  },
]);
