// What your people say to each other on the road, and what townsfolk say to
// each other when they think nobody is listening. Lines may use {name} (another
// of your people), {dead} (someone you lost), {beast} (one of your animals),
// {town}, {region} and {money}.

/** Who can say a line of a conversation. */
export interface Speaker {
  race?: 'human' | 'karuk' | 'thrum' | 'hollow';
  unique?: string;
}

/** A short exchange between two of your people. Lines alternate a, b, a, b. */
export interface Convo {
  a?: Speaker;
  b?: Speaker;
  when?: 'night' | 'day' | 'hungry' | 'poor' | 'rich' | 'rain' | 'hurt' | 'town' | 'wild';
  lines: string[];
}

export const CHAT: Record<string, string[]> = {
  idle: [
    'My feet have stopped hurting. I think that\'s bad.',
    'Nice day. Nothing\'s tried to eat us for an hour.',
    'I dreamt about bread last night. Just bread. It was wonderful.',
    'Somebody\'s following us. No. Just the wind. Probably.',
    'If we die out here, nobody will even find the bones.',
    'I counted the pieces of the moon again last night. Still seven.',
    'My mother said I\'d come to nothing. She was nearly right.',
    'Water, food and a roof. Two out of three would be nice.',
    'I could sleep for a week.',
    'Keep your eyes open. The waste looks empty right up until it isn\'t.',
    'Sand in my boots. Sand in my teeth. Sand in places I won\'t mention.',
    'How far have we walked? Don\'t answer. I don\'t want to know.',
    'One day someone will write songs about us. Short ones.',
    'When this is all over, I want a chair. A real one, with a back.',
    'I\'ve stopped noticing the smell. Mine or yours.',
    'Hear that? No? Good. Silence is the best sound out here.',
    'Everyone in the waste is running from something. I\'ve forgotten what I\'m running from.',
    'If anyone asks, we\'re merchants. Very well-armed merchants.',
    'The first rule of the road: never be the slowest. The second: never be the one carrying the food.',
    'My blade needs sharpening. So do I.',
    'Nobody gets old out here. The waste doesn\'t allow it.',
    'There\'s a stone in my boot. I\'ve decided it lives there now.',
    'I think I\'ve got used to the dust. That\'s the saddest thing I\'ve ever said.',
    'Every road goes somewhere worse. That\'s how you know it\'s a road.',
    'My knees are older than I am.',
    'Walk, fight, eat, sleep. It\'s a simple life. It\'s just short.',
    'The Makers had cities in the sky, they say. Look where it got them.',
    'Somebody tell a story. A good one, where nobody dies.',
    'Quiet out here. I don\'t trust quiet.',
    'One more hill. There\'s always one more hill.',
    'Why is it always uphill?',
    'I found a chit in my boot. I\'m rich.',
    'Keep walking. Standing still is how the waste gets you.',
    'I used to have a lucky charm. Somebody stole it. Which tells you something.',
    'When I was a child I wanted to be a caravan guard. Now I\'m worse paid and better armed.',
    'What I\'d give for a bath.',
    'Does anyone know a song? A cheerful one? No? Figures.',
    'Wind\'s changing. Smell that? Rain, or dunehounds.',
    'You know what I miss? Doors. Doors that lock.',
    'Nobody\'s tried to kill us today. I\'m almost insulted.',
  ],
  alone: [
    'Talking to myself again. At least the company\'s good.',
    'Just me, the road and the wind. The wind\'s winning.',
    'Nobody to watch my back. So I\'ll watch it twice.',
    'Should find some company. People who don\'t stab you. A short list.',
    'If I die out here, who\'ll tell anyone? The bats?',
    'Left foot. Right foot. Don\'t stop.',
    'I\'m not lonely. I\'m careful. There\'s a difference. I think.',
    'Maybe I should hire someone. Someone slow, so I\'m not the slowest.',
    'Hello, rock. Nice rock. Better company than most.',
    'I used to hate crowds. I\'d kill for a crowd now. Not literally. Probably.',
    'Still alive. Surprising everyone, including me.',
    'Somebody in a bar somewhere is looking for work. I should go and find them.',
  ],
  hungry: [
    'I\'m hungry. Is anyone else hungry? I\'m very hungry.',
    'My stomach\'s making noises a dunehound would be proud of.',
    'When did we last eat? Properly, I mean. Not chewing on a strap.',
    'I\'d eat a shellback raw. Shell and all.',
    'If we don\'t find food soon, I\'m eating my boots. Then yours.',
    'Somebody pack more food next time. Please.',
    'Is there anything left in the packs? Anything at all?',
    'Food. We need food. I\'m not being dramatic. I\'m being hungry.',
    'My belt\'s on its last hole.',
  ],
  starving: [
    'Can\'t... walk much further... without food.',
    'I\'m seeing things. A loaf of bread just waved at me.',
    'Food. Now. Or I lie down here and you can leave me.',
    'My hands are shaking. That\'s the hunger. Mostly.',
    'Anything. Dried meat, cactus, a boiled boot. Anything.',
    'If you\'ve been hiding food, now\'s the time to confess.',
  ],
  hurt: [
    'I think I\'m leaking.',
    'Could somebody look at this? It\'s the wrong colour.',
    'It\'s only a scratch. A big one. It goes all the way in.',
    'I need a bandage. Or a medic. Or a new body.',
    'Everything hurts. Even the parts that shouldn\'t.',
    'Don\'t worry about me. Worry about the blood. There\'s a lot of it.',
    'I\'ll be fine. Just walk slower. Much slower.',
    'Remind me why we fight things.',
  ],
  'hurt.machine': [
    'Damage report: significant. Repair kits recommended.',
    'My left side is making a noise. It should not make a noise.',
    'Plating breached. I am, as you say, fine.',
    'Joint integrity falling. I will limp with dignity.',
    'Please do not look at the sparks. They are private.',
  ],
  'hurt.hive': [
    '*click* Shell-is-cracked.',
    '*hum* Hurts. Hurts-is-a-new-word.',
    'Leaking. *click* Leaking-is-bad.',
  ],
  'hungry.hive': [
    '*click* Hungry. The-hive-would-feed-us.',
    'Resin? Anyone-has-resin?',
    '*hum* Belly-hums-louder-than-one.',
  ],
  'starving.hive': [
    '*a weak hum* ...Food...',
    '*click* ...One-must-eat. Soon.',
  ],
  'weather.machine': [
    'Atmospheric conditions: hostile.',
    'Particulates in my joints. Again.',
    'I will need cleaning after this. Thoroughly.',
  ],
  'weather.hive': [
    '*click* Sky-is-angry.',
    '*hum* Shell-is-good-in-bad-weather. Soft-skin-is-not.',
  ],
  'night.machine': [
    'It is dark. I will watch. I always watch.',
    'My eyes adjust to the dark. Yours do not. Stay near me.',
    'Night. The part of the day when organics trip over things.',
  ],
  'night.hive': [
    '*hum* Dark-is-quiet. Quiet-is-not-good.',
    '*click* Stars. Too-many-to-count.',
  ],
  'town.machine': [
    'Many organics. I will be polite. It is expected.',
    'My records of {town} are old. I am updating them.',
    'They are staring at me. I am used to it. I will stare back, politely.',
  ],
  'town.hive': [
    '*hum* Big-hive-of-soft-ones.',
    'Soft-ones-stare. *click* Soft-ones-always-stare.',
  ],
  'base.machine': [
    'Home. I have not had one before. I am told this is it.',
    'I have inspected the walls. They will do. Mostly.',
  ],
  'base.hive': [
    '*hum-hum* Hive! Small, but hive.',
    '*click* Home-smells-of-us. Good.',
  ],
  'poor.machine': [
    'Our funds are insufficient. I have run the numbers several times, hoping.',
    'We have {money} chits. That is not a figure. That is a warning.',
  ],
  'poor.hive': [
    '*click* Chits-are-few. Soft-ones-care-about-chits. Strange.',
  ],
  'alone.machine': [
    'Alone. I have been alone before. I did not care for it.',
    'Talking to myself is inefficient. I do it anyway.',
    'No one to watch. I will watch the road.',
  ],
  'alone.hive': [
    '*hum* One-is-alone. One-hums-for-one.',
    '*click* No-hive. No-squad. Only-one.',
  ],
  'mourn.machine': [
    'I have added {dead} to the names I say each night.',
    '{dead} once asked me if I could cry. I said no. I was mistaken.',
    'The last thing {dead} said to me was about boots. I wish it had been about something else.',
  ],
  'mourn.hive': [
    '*hum* {dead}-is-not-humming. One-listens-anyway.',
    '*click* One-still-counts-{dead}. Habit.',
  ],
  after_fight_alone: [
    'Still standing. Just.',
    'That\'s what you get.',
    'Nobody saw that. Good.',
    'Should have stayed on the road.',
  ],
  'after_fight.machine': [
    'Threat resolved. Checking all of you for damage.',
    'Hostiles neutralised. I would like to stop doing that.',
    'Combat concluded. Everyone is accounted for.',
  ],
  'after_fight.hive': [
    '*hum* Many-struck-as-one.',
    '*click* All-counted. Good.',
    '*hum-hum* Small-hive-is-safe.',
  ],
  'after_fight_hurt.machine': [
    '{name} requires repair. Or its organic equivalent.',
    'Carry {name}. I will watch the road.',
  ],
  'after_fight_hurt.hive': [
    '*click* {name}-is-hurt. Carry-{name}.',
  ],
  'ally_down.machine': [
    '{name} is down. Responding.',
    'Protective protocol: {name}.',
  ],
  'ally_down.hive': [
    '*CLICK* {name}-is-down!',
    '*CLICK-CLICK* Protect-{name}!',
  ],
  'ally_dead.machine': [
    'No. Not {dead}.',
    '{dead} has stopped. {dead} has stopped.',
  ],
  'ally_dead.hive': [
    '*a long, low hum*',
    '*CLICK* {dead}-is-gone!',
  ],
  heavy: [
    'What\'s in this pack? Rocks? It\'s rocks, isn\'t it?',
    'I\'m carrying half the waste on my back.',
    'If I walk any slower I\'ll be going backwards.',
    'Next town, we sell something. Anything. Me, if need be.',
    'My spine is filing a complaint.',
    'This pack weighs more than I do.',
    'Could someone else carry the iron for once?',
  ],
  poor: [
    'We\'re down to our last few chits. Just saying.',
    'I\'ve seen beggars with fuller purses.',
    'Empty purse, empty stomach. At least they match.',
    'We need money. Honest work, if we can find it. The other kind, if we can\'t.',
    'How much for a bowl of stew? More than we\'ve got, that\'s how much.',
    'I could sell my sword. Then I\'d be poor and unarmed. That\'s worse.',
    'There\'s always work for people who can swing a blade. That\'s the trouble.',
  ],
  rich: [
    'We\'ve got more chits than sense. Let\'s keep it that way.',
    'A purse this heavy attracts the wrong kind of friends.',
    'Remember when we couldn\'t afford bread? Me neither. Let\'s keep forgetting.',
    'All this money and my feet still hurt.',
    'Rich enough to buy a town. Too smart to live in one.',
  ],
  wanted: [
    'Keep your hood up. There\'s a price on my head, and it isn\'t small.',
    'Every guard in the waste has my face on a scrap of paper. It\'s not a good likeness.',
    'If we pass a patrol, I\'m not here. I\'m a very tall shadow.',
    'Somebody\'s going to try to collect on me one of these days.',
    'They want me in chains. They\'ll have to catch me first.',
    'Is my bounty going up? It feels like it\'s going up.',
  ],
  shackled: [
    'These shackles rub. Every step, they rub.',
    'Someday I\'ll take these chains off. Then I\'ll put them on someone who deserves them.',
    'Don\'t look at me. Slaves aren\'t supposed to be looked at.',
    'Work, sleep, work. The chains don\'t care which.',
    'Somebody out there has a key. I think about that a lot.',
  ],
  night: [
    'Stay close. Things hunt at night.',
    'I can\'t see my own feet.',
    'The moon\'s bright tonight. All seven pieces of it.',
    'Listen. Hear that? No, me neither. I hate that.',
    'We should make camp. Or keep walking. Both are terrible.',
    'Walking in the dark. Brilliant plan. Whose plan was this?',
    'At night the waste sounds like it\'s breathing.',
    'Something\'s out there. There\'s always something out there.',
  ],
  dawn: [
    'Morning. We lived. Good start.',
    'The sun\'s up. Let\'s see what wants to kill us today.',
    'Sunrise. Almost pretty, if you ignore everything else.',
    'New day. Same dust.',
    'Morning already? I only just closed my eyes.',
  ],
  base: [
    'Home. Such as it is.',
    'It\'s not much, but the walls are ours.',
    'Good to be back. Where\'s a bed? Any bed.',
    'Someone should build a proper kitchen.',
    'We need more walls. You can never have too many walls.',
    'Home. Where the raiders know where to find us.',
    'I like it here. Don\'t tell anyone. They\'ll come and raid it.',
  ],
  town: [
    '{town}. Civilisation. Or the next best thing.',
    'Keep your purse close. Towns are where the real thieves live.',
    'A bar, a bed and a meal. In that order.',
    'Mind the guards. They look bored, and bored guards make up crimes.',
    'I love a town. Walls, roofs, people who only rob you politely.',
    'Let\'s not start anything here. Not today.',
    'Smell that? Cooking. Real cooking.',
    '{town}. I\'ve heard stories. None of them good.',
    'Don\'t stare at the locals. They stare back.',
  ],
  hostile_town: [
    'Everyone\'s looking at us. I don\'t like how they\'re looking at us.',
    'We shouldn\'t be here. They want us dead here.',
    'Walk faster. Don\'t run. Running looks guilty.',
    'This is their town. We\'re the trouble they\'ve been waiting for.',
  ],
  sacked: [
    'This place was alive a few days ago.',
    'Burned. All of it. Who does this?',
    'Look at the doors. They didn\'t stand a chance.',
    'Ashes and flies. That\'s all a war leaves.',
  ],
  beast: [
    '{beast} is looking at me again. I think it wants my dinner.',
    'Somebody feed {beast} before it feeds itself.',
    'Who\'s a good beast? Not {beast}. {beast} bit me.',
    '{beast} smells terrible. It\'s the best of us.',
    '{beast} heard something. It always hears something first.',
  ],
  mourn: [
    'I keep thinking about {dead}.',
    '{dead} would have liked this view.',
    'It should have been me, not {dead}.',
    'Anyone else still hear {dead} laughing? No? Just me, then.',
    'We never buried {dead} properly. The waste did it for us.',
    '{dead} owed me ten chits. I\'d forgive it, if I could.',
    'To {dead}. Wherever they are, I hope there\'s shade.',
    'Nobody walks on the left now. {dead} always walked on the left.',
  ],
  after_fight: [
    'Is everyone still in one piece? Count your fingers.',
    'That was close. Too close.',
    'Check their pockets. They won\'t mind.',
    'Nobody\'s dead. I\'ll call that a good day.',
    'My hands are still shaking.',
    'Well. That happened.',
    'I hate this part. The quiet after.',
    'Next time, let\'s try talking first.',
    'Bandages. Everyone. Now.',
    'Anyone hurt? More than usual, I mean.',
  ],
  after_fight_hurt: [
    'Get {name} up. Quickly.',
    '{name}\'s down! Somebody carry them before the bats come.',
    'Don\'t leave {name}. We don\'t leave anyone.',
    '{name}, can you hear me? Stay with us.',
    'Somebody bandage {name}. I\'ll watch the road.',
  ],
  ally_down: [
    '{name}\'s down!',
    'Cover {name}!',
    'They got {name}!',
    'Get away from {name}!',
    'Protect {name}!',
  ],
  ally_dead: [
    '{dead}! No!',
    'They killed {dead}!',
    '{dead}... no. No, no, no.',
    'For {dead}!',
    '{dead} is gone!',
  ],
  weather_dust: [
    'Can\'t see my own hand.',
    'Cover your mouth. You\'ll be coughing sand for a week.',
    'Dust storm. Stay together. Anyone who wanders off stays off.',
    'The wind\'s got teeth today.',
  ],
  weather_rain: [
    'Rain! Real rain!',
    'Wet. Everything\'s wet. I\'d forgotten what that was like.',
    'Drink it while it lasts.',
    'At least it washes the blood off.',
  ],
  weather_fog: [
    'Stay close. I can\'t see a thing.',
    'Did you see that? A shape. In the fog. There.',
    'In fog like this, you hear things before you see them.',
    'Keep talking, so I know where you are.',
  ],
  weather_acid: [
    'It burns! Find a roof!',
    'The rain\'s eating my coat.',
    'Get under something! Anything!',
    'Cover your skin! Don\'t let it touch you!',
  ],
  weather_gas: [
    'Don\'t breathe. Or breathe less.',
    'The air tastes like rust and death.',
    'Masks on, if you\'ve got them.',
    'My eyes are streaming. This gas is poison.',
  ],
  weather_ash: [
    'Ash again. Somebody\'s always burning something.',
    'Like snow. Dead, grey snow.',
    'Breathe through your sleeve.',
    'Everything tastes of smoke.',
  ],
  weather_spores: [
    'Something\'s floating in the air. Don\'t breathe it in.',
    'These spores itch.',
    'The air\'s full of seeds. Or eggs. Don\'t think about it.',
    'I\'ve been sneezing for an hour.',
  ],
  weather_heat: [
    'My sword\'s too hot to hold.',
    'Water. Anyone. Water.',
    'The sun\'s trying to kill us personally.',
    'Find some shade before we cook.',
  ],
  weather_overcast: [
    'Grey sky. Grey land. Grey mood.',
    'Looks like rain. It won\'t, but it looks like it.',
    'At least the sun\'s taken the day off.',
  ],
};

/** Lines by people: what the horned, the hives and the machines say. */
export const RACE_CHAT: Record<string, string[]> = {
  karuk: [
    'Hah. A good day for a fight. They are all good days for a fight.',
    'My horns itch. That means weather, or war.',
    'Small ones walk so slowly. I am not complaining. I am observing.',
    'When I die, I want it to be loud.',
    'The Horn King would laugh at this squad. Then he would recruit it.',
    'A Karuk without a fight is a pot without a fire.',
    'I have not hit anything today. I feel unwell.',
    'Strong legs, strong back, strong horns. The rest is decoration.',
  ],
  thrum: [
    '*hum* Many-are-few-here. Few-is-strange.',
    '*click-click* Soft-ones-sweat. Why-sweat?',
    'Hum-is-quiet-here. Quiet-is-lonely.',
    'One-walks-far-from-the-Queen. Far-is-cold.',
    '*hum* Squad-is-small-hive. Small-hive-is-good.',
    'Sun-is-warm. Warm-is-good-for-shell.',
    'Soft-ones-talk-too-much. *click* This-one-is-talking-now. Hm.',
  ],
  hollow: [
    'Maintenance cycle overdue. I will continue regardless.',
    'I have calculated our odds. I will not share them.',
    'My joints require oil. Do not concern yourselves.',
    'I do not sleep, so I watch you sleep. You mumble.',
    'Query: why do organics sing? No answer required. I am only curious.',
    'Memory fragment: a garden, a child, a dog. Unrelated to current task.',
    'I am a thousand years old and I still do not understand money.',
    'Organic humour detected. I will laugh later, on my own.',
  ],
};

/** Lines about the country you walk through, keyed by region. */
export const REGION_CHAT: Record<string, string[]> = {
  flats: [
    'The Flats. Nothing, and then more nothing.',
    'Buttes, dust and dunehounds. You can say this for the Flats: they\'re consistent.',
    'Watch the ridges. Reavers like the high ground.',
    'Flat as a plate, and about as empty.',
  ],
  salt: [
    'The salt gets in everywhere. My teeth crunch.',
    'White as bone out here. It hurts to look at.',
    'Nothing grows on the salt. Nothing honest, anyway.',
    'Watch for Chainhouse caravans. They love a lone walker on the salt.',
  ],
  vale: [
    'Green. Actual green. I\'d forgotten what it looked like.',
    'The Vale. Farms, fields and priests counting every grain.',
    'Smell that? Wheat. Honest wheat.',
    'Keep the horned and the Hollows close. The Covenant burns what it doesn\'t like.',
  ],
  coast: [
    'The sea. Grey, cold and not for drinking.',
    'The fog comes in off the water. Things walk in it.',
    'Hear the surf? It\'s the only thing out here that never stops.',
    'Don\'t go down to the strand at night.',
  ],
  ember: [
    'The Emberlands. Everything here smells of smoke and prayer.',
    'A fire on every hill. The Covenant likes to be seen.',
    'Walk softly. The Covenant hears everything.',
    'The ground\'s warm. Something\'s burning under it.',
  ],
  highlands: [
    'Karuk country. Walk tall, or don\'t walk at all.',
    'The air\'s thin up here. Or I\'m getting old.',
    'Every flat rock up here is somebody\'s arena.',
    'Mountains. Wonderful. Nobody said anything about mountains.',
  ],
  thrumwood: [
    'Hear the hum? That\'s the hives. It gets into your teeth.',
    'Stalks taller than towers. What grows this big?',
    'The Thrum are friendly. Mostly. If you don\'t touch the resin.',
    'Blackcomb\'s out west. Don\'t go west.',
  ],
  mire: [
    'Mud to the knee. Lovely.',
    'Bloodflies, everywhere. Bandage early.',
    'Keep to the dry ground. What\'s in the water bites.',
    'The Mire. Where boots go to die.',
  ],
  ash: [
    'The Ashfields. Grey dust over everything.',
    'Stay together. The Mawkin hunt here.',
    'Every step, a puff of ash. Like walking on the dead.',
    'Don\'t eat anything you find out here. Don\'t ask what it is.',
  ],
  bonesea: [
    'Bones. Nothing but bones, all the way to the edge of the world.',
    'What killed these things? And is it still around?',
    'Walk between the ribs, and pray the hookbeaks aren\'t hungry.',
    'Some of these skeletons are bigger than towns.',
  ],
  rust: [
    'Machines everywhere. Dead ones, mostly. Mostly.',
    'Rust, wire and old Maker junk. Watch where you step.',
    'Hear that clicking? Rustspiders. Bring a club.',
    'The air tastes of iron here.',
  ],
  glass: [
    'Glass underfoot. Like walking on broken bottles for a living.',
    'The light plays tricks here. That tower isn\'t there. I checked.',
    'The Glasslands. Pretty, and it wants to kill you.',
    'Watch for green clouds. The rain here eats skin.',
  ],
};

/** Named people have their own things to say, and to say after a fight. */
export const UNIQUE_CHAT: Record<string, { idle: string[]; win?: string[] }> = {
  dunstan_smith: {
    idle: [
      'Good steel sings when you strike it. That sword of yours mumbles.',
      'I could forge a better blade than this out of a cart axle. I have done, once.',
      'When we settle, I want an anvil. A real one, not a rock with ambitions.',
      'Every blade I ever made is out here somewhere. I hope some of them are still sharp.',
      'That boy on my old forge. He\'ll have cracked the anvil by now.',
      'Hold still. Your buckle\'s on wrong. Everyone\'s buckle is on wrong.',
    ],
    win: ['Look at that edge. Chipped. I\'ll see to it tonight.', 'Their plate was rubbish. Concord surplus.'],
  },
  ysolde_unburnt: {
    idle: [
      'I used to preach about the light. Now I just walk in it.',
      'Every fire I see, I remember what I burned.',
      'If we meet Wardens, let me talk. Then let me fight.',
      'I don\'t pray any more. I keep watch. It\'s almost the same.',
      'The Covenant says the flame judges. I say people do, and badly.',
    ],
    win: ['May the flame judge them kindly. I didn\'t.', 'Put them on their sides. They\'ll live.'],
  },
  cressa_cartographer: {
    idle: [
      'Hold still. I\'m drawing this ridge. No, you\'re in the way of the ridge.',
      'That\'s not on any map. It will be.',
      'North-east. Always north-east. That\'s where the blanks are.',
      'I\'ve counted eleven fords on the Wending. Everyone else counts nine.',
      'If I die, somebody finish my maps. Don\'t colour them in badly.',
      'Three hundred paces to that rock. I\'d bet my boots on it. I\'d bet your boots on it.',
    ],
    win: ['I\'m marking this spot. \'Here be idiots.\''],
  },
  moth_lockbreaker: {
    idle: [
      'That lock back there? Four pins. Cheap. I didn\'t touch it. Much.',
      'Walk louder, would you? I\'m trying to be quiet next to you.',
      'I can hear coins in your pocket. Seven. No, eight.',
      'The Hand has long arms. I keep checking behind me.',
      'Retired, I said. Retired thieves still look at locks.',
      'Every door\'s just a question. I like questions.',
    ],
    win: ['Their purses are lighter now. Don\'t look at me. I\'m retired.'],
  },
  halima_needle: {
    idle: [
      'Stop picking at that. It\'ll heal crooked.',
      'I\'ve stitched worse than you. I\'ve stitched worse than all of you together.',
      'If you\'re going to get cut, get cut cleanly. It\'s easier to sew.',
      'How many bandages have we got? Not enough. Never enough.',
      'Chainfield taught me how bodies break. I\'d like to see a few of them heal.',
      'Drink water. All of you. I\'m not asking.',
    ],
    win: ['Nobody touch anything. I\'ll get to you in order of bleeding.', 'Sit down, all of you. Show me.'],
  },
  skarra_ninefights: {
    idle: [
      'Nine fights, and I\'m bored. Find me the tenth.',
      'Hah! This squad walks like it\'s afraid of the ground.',
      'When we find a real war, wake me. I\'ll be the one already fighting.',
      'You swing like you\'re apologising. Don\'t apologise. Hit.',
      'Guards stand still. I don\'t stand still.',
      'I miss the arena. The noise. The sand. The one who thought he\'d win.',
    ],
    win: ['Hah! Again!', 'That was nothing. Find me something bigger.', 'Ten. That was ten. I am counting now.'],
  },
  tunde_runaway: {
    idle: [
      'My sister\'s still in the east paddy. I count the days.',
      'Don\'t whistle like that. The overseers whistled like that.',
      'I still wake before dawn. Nine years, and my body thinks I\'m still in the fields.',
      'When we pass Chainfield, don\'t stop me. Or do. I don\'t know.',
      'The reeds taught me to be quiet. The dogs taught me to be quick.',
    ],
    win: ['Nobody\'s putting chains on me. Not today.'],
  },
  kamaria_liberator: {
    idle: [
      'Every chain I see, I want to break it. It makes shopping difficult.',
      'Two hundred and eleven freed. I keep count. I\'d like the count higher.',
      'Next time we see a Chainhouse caravan, we don\'t walk past it.',
      'I owe the overseer at Saltmere a visit.',
      'Free people walk differently. Watch them. It\'s in the shoulders.',
    ],
    win: ['Check them for keys. Slavers always carry keys.'],
  },
  lumen_lampkeeper: {
    idle: [
      'It is dusk somewhere. I should be lighting the lamps.',
      'The call from the Maker\'s Heart is louder tonight. It says my name very kindly.',
      'There was a dog. I do not know what it was for. I miss it.',
      'I keep a list of four names. I say them every night.',
      'When it is dark, stay near me. I glow slightly. I am told it is reassuring.',
    ],
    win: ['That was unpleasant. I will dim for a while.'],
  },
  echo_penitent: {
    idle: [
      'Walk in the light. I say it quietly now. It still counts.',
      'Brother Osric taught me the prayer. I say it for him, too.',
      'I mend things. Roofs, doors, straps. Tell me what is broken.',
      'The Covenant says machines have no souls. I have looked. I do not know where they keep theirs, either.',
      'Every morning I am not burned is a good morning.',
    ],
    win: ['I will mend what I can. Some of it is people.'],
  },
  ledger_accountant: {
    idle: [
      'Our purse holds {money} chits. I have counted it twice.',
      'Two hundred and six years of accounts, and nobody ever thanked the ledger.',
      'Interest is the cruellest thing organics ever invented. I admire it.',
      'I have calculated the value of this squad. Do not ask. It is not flattering.',
      'A chit saved is a chit we can spend later on bandages. I have also calculated the bandages.',
    ],
    win: ['Expenses: three bandages. Income: whatever is in their pockets. Acceptable.'],
  },
  piet_farmer: {
    idle: [
      'Good soil here. Wasted on rocks.',
      'Fifty-one harvests, and I never once had a day off.',
      'My sons went to the Field of Horns. I walk for them now.',
      'That\'s weedgrass. It chokes anything you plant. Remember that.',
      'Rain\'s coming. My knee\'s a better priest than any in Cinderhold.',
      'When we settle, I\'ll plant wheat. I don\'t know how to do anything else.',
    ],
    win: ['I\'m too old for this. I\'m also still standing.'],
  },
  brakka_cook: {
    idle: [
      'You are all too thin. It offends me.',
      'A warrior who cannot cook is hungry. A hungry warrior is dead.',
      'When we stop, I will make stew. You will like it. That is not a request.',
      'I smell goatling. Somebody catch it. I will do the rest.',
      'The Horn King\'s kitchen had a pot this big. I miss the pot.',
      'Salt. Fat. Fire. The rest is argument.',
    ],
    win: ['Good. Now we eat.', 'Fighting makes you hungry. Everything makes you hungry. That is why I cook.'],
  },
  wren_longshot: {
    idle: [
      'Something moving on the ridge. No. Just a rock. I\'d still have shot it.',
      'I miss my stool.',
      'Twelve years at the gate. I can hit a shellback\'s eye at a hundred paces.',
      'Fog makes me itchy. My finger, mostly.',
      'I\'ve never missed. I\'ve just been unlucky about what I aimed at.',
    ],
    win: ['Stay down. I\'ve got a bolt with your name on it. I\'ve got a lot of bolts.'],
  },
  nettle_ashchild: {
    idle: [
      'Don\'t walk behind me.',
      'I can smell a Mawkin camp a mile off. I\'m smelling one now. No. Gone.',
      'I don\'t eat meat. Don\'t ask me why. You really don\'t want to know.',
      'The drums. I still hear them some nights. Then I remember it\'s my heart.',
      'Keep the fire lit tonight. All night.',
    ],
    win: ['Don\'t eat them. I mean it. Nobody eats anybody.'],
  },
  vssara_hiveless: {
    idle: [
      '*hum* ...I. I-am-walking. The-word-is-still-strange.',
      'One-hears-no-Queen. Silence-is-loud.',
      'Squad-is-almost-hive. Almost. *click*',
      'One-carries-no-madness. One-has-checked. Many-times.',
      'Soft-ones-say-\'I\'-so-easily. How?',
    ],
    win: ['*CLICK* Many-strike-as-one. We-struck-as-one. Good.'],
  },
  tchikka_counter: {
    idle: [
      '*hum* Tchikka-counts-one-thousand-and-four-steps-since-the-last-rock.',
      'Soft-one-has-blinked-forty-times. Soft-one-is-tired?',
      'Nine-hundred-and-eleven-soft-people-counted. Still-none-know-why-they-walk-alone.',
      '*click* This-squad-walks-together. Tchikka-writes-that-down.',
      'The-Queen-will-want-a-report. Report: soft-people-complain-a-lot.',
    ],
    win: ['*hum* Tchikka-counts-the-fallen. Tchikka-counts-us. We-are-more. Good.'],
  },
  kesh_one_ear: {
    idle: [
      'Did I ever tell you about the time I robbed a Concord tax cart? It was a good story.',
      'A quarter. Always take a quarter. Take everything and they stop using the road.',
      'One of the young ones at the Roost would have knifed me by summer. Now they\'ll have to knife each other.',
      'Twenty years on the Crossroad road. I know every rock. That one\'s new.',
      'Honest work. Tried it once. Paid badly.',
      'I lost the ear to a Watch sergeant. He lost more. We don\'t talk about him.',
    ],
    win: ['Should\'ve paid the quarter.', 'Ha! Still got it. Both of it. The ear and the other thing.'],
  },
};

export const CONVOS: Convo[] = [
  { lines: ['Do you ever think about going home?', 'What home?', 'Fair.'] },
  { lines: ['What would you do with a thousand chits?', 'Eat. Then sleep. Then eat again.', 'Dream big.'] },
  { lines: ['Why do they call it the Sundered Waste?', '"The big dusty place where everything bites" wouldn\'t fit on the maps.'] },
  { lines: ['How many pieces is the moon in?', 'Seven.', 'I counted eight last night.', 'Then stop drinking the dustwine.'] },
  { lines: ['If I die, you can have my boots.', 'Your boots have holes in them.', 'Then I\'d better not die.'] },
  { lines: ['Are we lost?', 'No. We\'re exploring.', 'That\'s what lost people say.'] },
  { lines: ['Do you trust me?', 'I trust you to be exactly who you are.', '...Thanks?'] },
  { lines: ['Tell me something nice.', 'We\'re not dead.', 'That\'s a low bar.', 'And we cleared it.'] },
  { lines: ['I think that rock moved.', 'Rocks don\'t move.', 'Then what\'s that?', '...Walk faster.'] },
  { lines: ['What did you do, before all this?', 'Nothing I want to talk about.', 'Same.'] },
  { lines: ['Why do you carry that thing?', 'In case.', 'In case of what?', 'In case.'] },
  { lines: ['Remind me why we\'re going this way.', 'Because the other way was worse.', 'The other way is always worse.'] },
  { lines: ['One day we\'ll have a town of our own.', 'With walls?', 'Big walls.', 'I\'ll drink to that. When we have anything to drink.'] },
  { lines: ['Do you believe in the Ember?', 'I believe in fire. It keeps the bats off.', 'The priests would call that close enough.'] },
  { lines: ['Why did you throw in with us?', 'You were the only ones going somewhere.', 'We\'re not going anywhere.', 'You\'re going there fast.'] },
  { lines: ['Is it me, or is it hotter today?', 'It\'s you.', 'Thanks.'] },
  { lines: ['I heard the Makers could fly.', 'And now they\'re dust. Stay on the ground.'] },
  { lines: ['What\'s that smell?', 'Us.', 'Right.'] },
  { lines: ['You snore, you know.', 'I don\'t sleep. I keep watch with my eyes closed.'] },
  { lines: ['What\'s the worst thing you\'ve ever eaten?', 'Stew.', 'Which stew?', 'All of them.'] },
  { when: 'hungry', lines: ['Is there any food left?', 'There\'s a crust.', 'Share it?', 'It\'s a very small crust.'] },
  { when: 'hungry', lines: ['I\'d kill for a bowl of stew.', 'Don\'t say that out here. Somebody might take you up on it.'] },
  { when: 'poor', lines: ['How much money have we got?', 'Enough for one of us to eat.', 'Which one?', 'Let\'s not decide that yet.'] },
  { when: 'rich', lines: ['We\'ve got a lot of money, you know.', 'Shh. The waste can hear you.'] },
  { when: 'night', lines: ['Can you see anything?', 'No.', 'Good. Then nothing can see us either.', 'That\'s not how it works.', 'Let me have this.'] },
  { when: 'night', lines: ['Your turn to keep watch.', 'I always keep watch.', 'You were asleep last night.', 'I was watching my dreams.'] },
  { when: 'rain', lines: ['Rain!', 'Real rain?', 'Real rain.', 'Nobody tell the Covenant. They\'ll tithe it.'] },
  { when: 'hurt', lines: ['You look terrible.', 'You should see the other one.', 'I did. They look better than you.'] },
  { when: 'town', lines: ['Keep your hands where the guards can see them.', 'Where should I keep them?', 'Where the guards can see them.'] },
  { when: 'wild', lines: ['How far to the next town?', 'Two days.', 'You said two days yesterday.', 'And I was right yesterday, too.'] },
  // people
  { a: { race: 'human' }, b: { race: 'karuk' }, lines: ['Do your horns hurt?', 'Does it hurt, not having them?', '...No?', 'Then we are both lucky.'] },
  { a: { race: 'human' }, b: { race: 'karuk' }, lines: ['How tall are you, anyway?', 'Tall enough to see trouble before you do.', 'And to get hit by it first.', 'Hah. Yes. I like that part.'] },
  { a: { race: 'human' }, b: { race: 'hollow' }, lines: ['Do you dream?', 'I defragment. It is similar. There are fewer falling teeth.'] },
  { a: { race: 'human' }, b: { race: 'hollow' }, lines: ['How old are you?', 'Older than your language. Younger than the mountains. Around there.'] },
  { a: { race: 'human' }, b: { race: 'hollow' }, lines: ['Doesn\'t it bother you, never eating?', 'Doesn\'t it bother you, eating? Every day? Forever?', '...Put like that.'] },
  { a: { race: 'human' }, b: { race: 'thrum' }, lines: ['What does the hum sound like to you?', '*hum* Like-home. Like-many-voices. Like-your-heart-but-louder.', 'That sounds nice.', 'It-is. Soft-one-should-try.', 'I can\'t hum that low.', '*click* Sad.'] },
  { a: { race: 'karuk' }, b: { race: 'hollow' }, lines: ['Machine. Can you feel pain?', 'I register damage.', 'That is not what I asked.', 'Then yes. A little.'] },
  { a: { race: 'karuk' }, b: { race: 'karuk' }, lines: ['Have you fought in the Pit?', 'Of course.', 'Did you win?', 'I am here, am I not?'] },
  { a: { race: 'hollow' }, b: { race: 'hollow' }, lines: ['Query: do you remember the Makers?', 'Fragments. A voice. A garden.', 'I remember a garden too.', 'Perhaps it was the same garden.'] },
  { a: { race: 'thrum' }, b: { race: 'thrum' }, lines: ['*hum*', '*hum-hum*', '*click* ...Yes.', '*hum* Yes.'] },
  // named people
  { a: { unique: 'echo_penitent' }, b: { unique: 'ysolde_unburnt' }, lines: ['You are the Warden who would not burn me.', 'I\'m the Warden who didn\'t stop the others.', 'You did what you could.', 'It wasn\'t enough.', 'It was enough for me to be here. That is most of the evening prayer.'] },
  { a: { unique: 'tunde_runaway' }, b: { unique: 'kamaria_liberator' }, lines: ['They say you freed two hundred on the salt.', 'Two hundred and eleven. And none of them was your sister.', 'Not yet.', 'Not yet.'] },
  { a: { unique: 'halima_needle' }, b: { unique: 'tunde_runaway' }, lines: ['You\'re from Chainfield. I can tell by the way you stand.', 'The east paddy. Nine years.', 'I was the healer there. I might have stitched you.', 'You did. My hand. I remember your face.', 'I don\'t remember yours. I\'m sorry. There were so many.'] },
  { a: { unique: 'skarra_ninefights' }, b: { unique: 'brakka_cook' }, lines: ['Brakka. You were Horn Guard.', 'I was.', 'And now you cook.', 'And now I cook. Eat, then tell me it was a waste.', '...It was not a waste.'] },
  { a: { unique: 'ledger_accountant' }, b: { unique: 'lumen_lampkeeper' }, lines: ['Lumen. How long since your family?', 'Nine hundred and eighty-one years. And four days.', 'I have kept accounts for two hundred and six. It feels longer.', 'Everything feels longer when you count it.'] },
  { a: { unique: 'tchikka_counter' }, b: { unique: 'vssara_hiveless' }, lines: ['*hum* Vssara-was-Blackcomb.', '*click* ...Yes.', 'Tchikka-counts-no-madness-in-Vssara. Zero.', '...Zero?', 'Zero. Tchikka-is-very-good-at-counting.'] },
  { b: { unique: 'nettle_ashchild' }, lines: ['Why don\'t you ever eat the meat?', 'Because I know what else goes in the pots at Gnawbone.', 'We\'re not at Gnawbone.', 'You never know where you are, with meat.'] },
  { a: { unique: 'kesh_one_ear' }, lines: ['Did I ever tell you about the time I robbed a Concord tax cart?', 'Yes.', 'Twice?', 'Four times.', 'Well. It gets better every time.'] },
  { b: { unique: 'cressa_cartographer' }, lines: ['Are we lost?', 'I have never been lost in my life.', 'Then where are we?', 'Somewhere nobody has drawn yet. That\'s different.'] },
  { b: { unique: 'moth_lockbreaker' }, lines: ['Has anyone seen my purse?', 'Front pocket. Left.', '...Oh. Thanks.', 'Keep it in the front pocket. I\'m retired. Other people aren\'t.'] },
  { a: { unique: 'dunstan_smith' }, lines: ['Give me your sword.', 'Why?', 'Because I can hear it from here. It\'s chipped.', 'Can you fix it?', 'I can fix anything with an anvil. I haven\'t got an anvil.'] },
  { b: { unique: 'piet_farmer' }, lines: ['What are you looking at, Piet?', 'The soil.', 'It\'s dirt.', 'It\'s the best dirt I\'ve seen in a month. Don\'t insult it.'] },
  { a: { unique: 'wren_longshot' }, lines: ['Don\'t move.', 'What is it?', 'Nothing. I just like it when people don\'t move.'] },
  { b: { unique: 'brakka_cook' }, when: 'hungry', lines: ['Brakka, is there anything to eat?', 'There is always something to eat.', 'Anything good?', 'Ah. That is a different question.'] },
  { a: { unique: 'halima_needle' }, when: 'hurt', lines: ['Sit down. You\'re bleeding.', 'It\'s nothing.', 'It\'s something. I\'ll decide when it\'s nothing.'] },
  { b: { unique: 'ledger_accountant' }, lines: ['How much money have we got, Ledger?', '{money} chits.', 'Is that good?', 'It is a number. Numbers are neither good nor bad. This one is bad.'], when: 'poor' },
  { a: { unique: 'skarra_ninefights' }, b: { race: 'human' }, lines: ['Small one. Fight me.', 'What? Now?', 'Not now. Later. When you are better.', 'When will that be?', 'Hah! Good question.'] },
  { b: { unique: 'lumen_lampkeeper' }, when: 'night', lines: ['You\'re glowing.', 'Yes. I am told it is reassuring.', 'It is, a bit.', 'Thank you. I have been practising.'] },
  { b: { unique: 'vssara_hiveless' }, lines: ['Are you all right, Vssara?', '*click* I-am... I. I-am-all-right.', 'You said "I".', '*hum* ...I-did.'] },
  { a: { unique: 'tchikka_counter' }, lines: ['*hum* Soft-one-has-said-\'fine\'-thirty-one-times-today.', 'I\'m fine.', 'Thirty-two.'] },
  { a: { unique: 'echo_penitent' }, b: { race: 'human' }, lines: ['Would you like to hear the evening prayer?', 'Is it long?', 'It is four lines.', 'Go on, then.', 'Thank you. Nobody has ever said "go on, then".'] },
  { b: { unique: 'tunde_runaway' }, when: 'night', lines: ['You\'re awake again.', 'Always, before dawn.', 'Still counting?', 'Always.'] },
];

/** What townsfolk say to each other, by faction. */
export const TOWN_TALK: Record<string, string[][]> = {
  default: [
    ['Did you hear? Reavers hit a caravan on the east road.', 'Again? That\'s the third this month.', 'The Watch says it\'s handled.', 'The Watch says everything\'s handled.'],
    ['Water\'s gone up to three chits a cup.', 'Three? For well water?', 'Well water with a view.'],
    ['Who are the strangers?', 'Don\'t know. Don\'t ask. Don\'t stare.'],
    ['My cousin went to Aurum to get rich.', 'Did he?', 'He got a debt. Very fancy. Gold edges.'],
    ['Busy day?', 'Every day\'s busy when nobody pays you.'],
    ['Bar\'s open late tonight.', 'Bar\'s open late every night.', 'That\'s why I like it.'],
    ['Heard there\'s a price on some outlaw\'s head.', 'There\'s always a price on somebody.', 'This one\'s big.', 'Then so is the outlaw.'],
    ['Looks like weather.', 'Looks like weather every day.', 'And every day I\'m right.'],
  ],
  concord: [
    ['Has House Venn paid its tithe to the palace?', 'House Venn pays nothing. House Venn is owed.'],
    ['Another contract signed today.', 'For what?', 'For another contract.'],
    ['Mind the stranger. Probably unlicensed.', 'Everyone\'s unlicensed until they pay.'],
    ['The Lords are buying Relic Cores again.', 'What for?', 'Nobody asks the Lords what for.'],
    ['Did you bow to the Lord this morning?', 'Twice.', 'Good. Once looks like you don\'t mean it.'],
  ],
  chainhouse: [
    ['Good stock came in from the Barrens.', 'Healthy?', 'Healthy enough to stand. Priced to move.'],
    ['The Unchained hit another caravan.', 'Double the guards.', 'We already doubled them.', 'Then double them again.'],
    ['Somebody left a pen open last night.', 'Who?', 'That\'s what the overseer wants to know.'],
  ],
  ember: [
    ['The Pyre burned bright this morning.', 'The Ember is pleased.', 'Or the woodcutters were early.'],
    ['An Inquisitor came by. Asked about horned ones.', 'What did you tell him?', 'That I\'d never seen one. Which is true, today.'],
    ['The tithe\'s due.', 'The tithe\'s always due.', 'That\'s what makes it a tithe.'],
    ['Walk in the light, sister.', 'And you, brother. Mind the step. It\'s dark by the well.'],
  ],
  karuk: [
    ['Did you see the fight in the Pit?', 'Which one?', 'The one where the small one won.', 'Hah! Nobody will let the big one forget it.'],
    ['The Horn King is old.', 'Say that in the hall, and see how old you get.'],
    ['You fought well yesterday.', 'I lost.', 'You lost well. That is also fighting.'],
    ['Hungry?', 'Always.', 'Good. Hungry is honest.'],
  ],
  thrum: [
    ['*hum-hum* Resin-stores-are-full.', '*click* Queen-is-pleased.', 'Queen-is-always-pleased-with-full-stores.'],
    ['Soft-ones-came-to-trade.', '*hum* Soft-ones-always-come. Soft-ones-always-want-resin.'],
    ['*click-click*', '*hum*', '*click* ...Yes. Tomorrow.'],
  ],
  delvers: [
    ['Find anything down there?', 'A door. A locked one.', 'Did you open it?', 'Did I come back with all my fingers? Then no.'],
    ['The lamps are low.', 'Then fill them. Nobody goes out with a low lamp.'],
    ['Whose name is chalked on the board?', 'Nobody you know.', 'Everybody\'s somebody I know, out here.'],
  ],
  hollows: [
    ['STATUS REPORT.', 'NOMINAL. MOSTLY.', 'Mostly is not a status.', 'It is today.'],
    ['The Heart hummed last night.', 'It hums every night.', 'It was louder last night.'],
    ['An organic asked me the time.', 'What did you tell it?', 'All of it. It left before I had finished.'],
  ],
  scorched: [
    ['The leaf shipment\'s late.', 'The Hand won\'t like that.', 'The Hand doesn\'t like anything. That\'s why it\'s the Hand.'],
    ['See the strangers?', 'I see nothing. I\'m from Mudwater.'],
    ['Somebody\'s boat went missing.', 'Whose?', 'Don\'t know. The swamp does.'],
  ],
  unchained: [
    ['Any word from the east paddy?', 'Three more got out. Two made it.', 'Two is two.'],
    ['Hunters were seen on the reed road.', 'Then we move the camp tonight.'],
    ['I had a dream I was back in the pens.', 'We all have that dream.', 'Does it stop?', 'No. But you stop waking up screaming.'],
  ],
  ironcoin: [
    ['Contract\'s up at the end of the month.', 'Renewing?', 'If they pay more. They always pay more.'],
    ['Who are we fighting this week?', 'Whoever didn\'t pay us.'],
  ],
  reavers: [
    ['Slow day on the road.', 'Slow days are poor days.', 'Then let\'s go and find somebody fast.'],
    ['Kesh is telling the tax cart story again.', 'Which version?', 'The one where he fights nine men.', 'It was two men and a mule.'],
  ],
  starvelings: [
    ['Anything?', 'Nothing.', 'Tomorrow, then.', 'Tomorrow.'],
    ['I found a root.', 'Share?', '...Half.'],
  ],
  mawkin: [
    ['*sniff* ...Meat is near.', 'Wait for dark.'],
    ['The pot is empty.', 'Not for long.'],
  ],
  drifters: [
    ['The Watch is hiring again.', 'What happened to the last lot?', 'Nobody asks what happened to the last lot.'],
    ['Heard someone found relics out past the butte.', 'Heard someone never came back from the butte.', 'Same someone.'],
  ],
};
